/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-27 14:10:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import com.project.ecommerce.dao.OrderDAO;
import com.project.ecommerce.model.Order;
import com.project.ecommerce.dao.CustomerDAO;
import com.project.ecommerce.model.CustomerSession;
import com.project.ecommerce.model.Product;
import com.project.ecommerce.dao.ProductDAO;
import com.project.ecommerce.dao.BrandDAO;
import java.util.ArrayList;
import com.project.ecommerce.model.Category;
import com.project.ecommerce.model.Brand;
import com.project.ecommerce.model.Customer;
import com.project.ecommerce.model.Cart;
import com.project.ecommerce.dao.CategoryDAO;
import java.util.List;

public final class MyOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Views/header.jsp", Long.valueOf(1700416332999L));
    _jspx_dependants.put("/Views/Footer.jsp", Long.valueOf(1699958121022L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.ecommerce.dao.BrandDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Category");
    _jspx_imports_classes.add("com.project.ecommerce.dao.ProductDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Customer");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("com.project.ecommerce.model.Brand");
    _jspx_imports_classes.add("com.project.ecommerce.model.CustomerSession");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CategoryDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CustomerDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Product");
    _jspx_imports_classes.add("com.project.ecommerce.model.Order");
    _jspx_imports_classes.add("com.project.ecommerce.dao.OrderDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Đơn Hàng || ShopSmartPhone</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\"\n");
      out.write("	integrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\n");
      out.write("		integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\n");
      out.write("		integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\n");
      out.write("	integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"../Css/Fstyle.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\n");
      out.write("	crossorigin=\"anonymous\"> \n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\"\n");
      out.write("	integrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	\n");
      out.write("<link rel=\"stylesheet\" href=\"../Css/Fstyle.css\">\n");
      out.write("<script src=\"../Js/header.js\"></script>\n");
      out.write("<script>\n");
      out.write("	$(document).ready(function() {\n");
      out.write("		\n");
      out.write("		$(\"#btnSearch\").click(function() {\n");
      out.write("			var textSearch = $(\"#text-Search\").val()\n");
      out.write("			var flag=0\n");
      out.write("			if(textSearch.trim()==''){\n");
      out.write("				flag=1\n");
      out.write("				window.location.href = \"http://localhost:8090/ShopSmartPhone/Views/Home.jsp\"\n");
      out.write("					\n");
      out.write("			}\n");
      out.write("			if(flag==0){\n");
      out.write("				$.ajax({\n");
      out.write("						type : \"post\",\n");
      out.write("						url : \"/ShopSmartPhone/searchServlet\",\n");
      out.write("						data : {\n");
      out.write("								textSearch : textSearch\n");
      out.write("						},\n");
      out.write("						success : function(response) {\n");
      out.write("							window.location.href = \"http://localhost:8090/ShopSmartPhone/Views/ListofSearch.jsp\"\n");
      out.write("								}\n");
      out.write("						});\n");
      out.write("			}\n");
      out.write("		})\n");
      out.write("		$(\"#btnLoginHeader\").click(function(){\n");
      out.write("			  $('#LoginModal').modal('show')\n");
      out.write("				 $(\"#loginModalClick\").trigger('click')\n");
      out.write("		})\n");
      out.write("		$(\"#btnRegisterHeader\").click(function(){\n");
      out.write("			 $('#LoginModal').modal('show')\n");
      out.write("			 $(\"#registerModalClick\").trigger('click')\n");
      out.write("		})\n");
      out.write("		$(\"#btnCustomer\").click(function(){\n");
      out.write("			 var idCustomer= $(this).attr(\"data-idCustomer\")\n");
      out.write("			 var nameCustomer= $(this).attr(\"data-nameCustomer\")\n");
      out.write("			 var phoneCustomer= $(this).attr(\"data-phoneCustomer\")\n");
      out.write("			 var emailCustomer= $(this).attr(\"data-emailCustomer\")\n");
      out.write("			 var addressCustomer= $(this).attr(\"data-addressCustomer\")\n");
      out.write("			 $(\"#textNameCustomer\").val(nameCustomer)\n");
      out.write("			 if(phoneCustomer=='null'){\n");
      out.write("				 $(\"#textPhoneCustomer\").html('')\n");
      out.write("			 } else {\n");
      out.write("				 $(\"#textPhoneCustomer\").val(phoneCustomer)\n");
      out.write("			 }\n");
      out.write("			 if(phoneCustomer=='null'){\n");
      out.write("				 $(\"#textAddressCustomer\").html('')	\n");
      out.write("			 } else {\n");
      out.write("				 $(\"#textAddressCustomer\").val(addressCustomer)	\n");
      out.write("			 }\n");
      out.write("			\n");
      out.write("			 $(\"#textEmailCustomer\").val(emailCustomer)\n");
      out.write("			 \n");
      out.write("			 $(\"#btnEditCustomer\").val(idCustomer)\n");
      out.write("			 $('#CustomerModal').modal('show')\n");
      out.write("					$(\"#textNameCustomer\").keypress(function(){\n");
      out.write("					$(\"#name_alertCustomer\").html('')\n");
      out.write("					})\n");
      out.write("					$(\"#textPhoneCustomer\").keypress(function(){\n");
      out.write("						$(\"#phone_alertCustomer\").html('') \n");
      out.write("					})\n");
      out.write("					$(\"#textAddressCustomer\").keypress(function(){\n");
      out.write("						$(\"#address_alertCustomer\").html('') \n");
      out.write("					})\n");
      out.write("			 $(\"#btnEditCustomer\").click(function(){\n");
      out.write("						var flag=0\n");
      out.write("						var id= $(\"#btnEditCustomer\").val()\n");
      out.write("						var name= $(\"#textNameCustomer\").val()\n");
      out.write("						var phone= $(\"#textPhoneCustomer\").val()\n");
      out.write("						var address= $(\"#textAddressCustomer\").val()\n");
      out.write("						var dataButton= $(this).attr(\"data-button\")\n");
      out.write("						  if(address.trim() ==''){\n");
      out.write("								$(\"#address_alertCustomer\").html('(*)Địa chỉ không được để trống!');\n");
      out.write("								flag=1\n");
      out.write("							} \n");
      out.write("						if(name.trim()==''){\n");
      out.write("							$(\"#name_alertCustomer\").html(\"(*)Họ và tên không được để trống! \")\n");
      out.write("							flag=1\n");
      out.write("						}\n");
      out.write("						if(phone.trim()==''){\n");
      out.write("							$(\"#phone_alertCustomer\").html(\"(*)Số điện thoại không được để trống! \")\n");
      out.write("							flag=1\n");
      out.write("						} \n");
      out.write("						if(phone.trim()!='' && phone.length>12 || phone.length<8){\n");
      out.write("				         	$(\"#phone_alertCustomer\").html('(*)Số điện thoại phải trên 8 số và dưới 12 số')\n");
      out.write("				         	flag=1;\n");
      out.write("				         }\n");
      out.write("						if(flag==0){\n");
      out.write("							\n");
      out.write("							$.ajax({\n");
      out.write("								type: \"post\",\n");
      out.write("								url: \"/ShopSmartPhone/editProfileServlet\",\n");
      out.write("								data: {\n");
      out.write("									id : id,\n");
      out.write("									nameCustomer : name,\n");
      out.write("									phoneCustomer : phone,\n");
      out.write("									addressCustomer : address,\n");
      out.write("									dataButton : dataButton\n");
      out.write("								},\n");
      out.write("								success : function(response){\n");
      out.write("									if(response==\"success\"){\n");
      out.write("										window.location.replace(\"http://localhost:8090/ShopSmartPhone/Views/Home.jsp\");\n");
      out.write("										}\n");
      out.write("									else if(response==\"wrong\"){\n");
      out.write("										$(\"#address_alertCustomer\").html(\"(*)Đăng kí không thành công! \")\n");
      out.write("									} \n");
      out.write("									\n");
      out.write("								}\n");
      out.write("							});\n");
      out.write("						}\n");
      out.write("					})\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("			$(\"#change-password\").click(function() {	\n");
      out.write("						$(\"#CustomerModal\").modal('hide')\n");
      out.write("						$(\"#changePassword\").modal('show')\n");
      out.write("						$(\"#oldpass\").keypress(function() {\n");
      out.write("						$(\"#passwordResult\").html('');\n");
      out.write("						});\n");
      out.write("						$(\"#newpass\").keypress(function() {\n");
      out.write("							$(\"#newPasswordResult\").html('');\n");
      out.write("						});\n");
      out.write("						$(\"#renewpass\").keypress(function() {\n");
      out.write("							$(\"#repasswordResult\").html('');\n");
      out.write("						});\n");
      out.write("						$(\"#resetChange\").click(function(){\n");
      out.write("							$(\"#oldpass\").val('')\n");
      out.write("							$(\"#newpass\").val('')\n");
      out.write("							$(\"#renewpass\").val('')\n");
      out.write("						})\n");
      out.write("						$(\"#btnChange\").click(function(){\n");
      out.write("							\n");
      out.write("								var oldpass= $(\"#oldpass\").val()\n");
      out.write("								var newpass = $(\"#newpass\").val()\n");
      out.write("								var renewpass = $(\"#renewpass\").val()\n");
      out.write("								var dataButton = $(this).attr(\"data-button\")\n");
      out.write("								var id = $(this).attr(\"data-id\")\n");
      out.write("								var flag = 0;\n");
      out.write("								\n");
      out.write("								if(oldpass.trim()==''){\n");
      out.write("									$(\"#passwordResult\").html('(* Bạn cần phải điền mật khẩu cũ của bạn *)')\n");
      out.write("									flag = 1\n");
      out.write("								}\n");
      out.write("								if(newpass.trim()==''){\n");
      out.write("									$(\"#newPasswordResult\").html('(* Bạn cần phải điền mật khẩu mới *)')\n");
      out.write("									flag = 1\n");
      out.write("								}	\n");
      out.write("								if(renewpass.trim()==''){\n");
      out.write("									$(\"#repasswordResult\").html('(* Bạn cần xác nhận lại mật khẩu *)')\n");
      out.write("									flag = 1\n");
      out.write("								}\n");
      out.write("								if(newpass.trim()!='' && newpass.length < 8 || newpass.length > 50){\n");
      out.write("									$(\"#newPasswordResult\").html('(* Mật khẩu phải >=8 chars và <= 30 kí tự *)')\n");
      out.write("									flag = 1\n");
      out.write("								}\n");
      out.write("								if(newpass.trim() != renewpass.trim()){\n");
      out.write("									$(\"#repasswordResult\").html('(*  Mật khẩu không trùng. Vui lòng xác thực lại *) ')\n");
      out.write("									flag = 1\n");
      out.write("								}if(flag == 0){\n");
      out.write("									 $.ajax({\n");
      out.write("										 	type: \"post\",\n");
      out.write("								        	url:\"/ShopSmartPhone/editProfileServlet\",\n");
      out.write("								        	data:{\n");
      out.write("								        			id : id,\n");
      out.write("								        			oldpass : oldpass,\n");
      out.write("								        			newpass : newpass,\n");
      out.write("								        			dataButton : dataButton\n");
      out.write("								        		},\n");
      out.write("								            success: function (response) {\n");
      out.write("								            	if(response == \"success\"){\n");
      out.write("								            		$(\"#changePassword\").modal('hide')\n");
      out.write("								            		$(\"#changeSuccess\").modal('show')\n");
      out.write("								            		\n");
      out.write("								            		$('#btnSuccess').click(function(){\n");
      out.write("								            			$('.modal-backdrop').remove()\n");
      out.write("								            		})	\n");
      out.write("								            	}\n");
      out.write("								            	else if (response == \"wrong\"){\n");
      out.write("								            		$(\"#passwordResult\").html('(* Mật khẩu hiện tại không đúng *)')\n");
      out.write("								            	}\n");
      out.write("								            	else if (response == \"fail\"){\n");
      out.write("								            		$(\"#passwordResult\").html('(* Đã có lỗi xảy ra *)')\n");
      out.write("								            	}\n");
      out.write("								            } \n");
      out.write("								            \n");
      out.write("											});			\n");
      out.write("									}\n");
      out.write("								});\n");
      out.write("								\n");
      out.write("					});\n");
      out.write("		\n");
      out.write("		$(\"#btnLogout\").click(function(){\n");
      out.write("			window.location.replace(\"http://localhost:8090/ShopSmartPhone/logOutServlet?role=customer\");\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("})\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- -------Khai báo phương thức------------ -->\n");
      out.write("	");

		CategoryDAO categoryDAO = new CategoryDAO();
		Category category = new Category();
		BrandDAO brandDAO = new BrandDAO();
		Brand brand = new Brand();
		Customer customer= new Customer();
		CustomerDAO customerDAO= new CustomerDAO();

		Cart cart = (Cart) session.getAttribute("cart");
		if (cart == null) {
			cart = new Cart();
			session.setAttribute("cart", cart);
			
		}
		String register = "Đăng kí";
		String login = "Đăng nhập";
		Customer user = (Customer) session.getAttribute("customerSession");

		if (user != null) {
			customer= customerDAO.customerByID(user.getId());
			register = customer.getName();
			login = "Đăng xuất";
		}
	
      out.write("\n");
      out.write("<!-- Header - start -->\n");
      out.write("<header class=\"header container\" id=\"header-content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Logo, Shop-menu - start -->\n");
      out.write("		<div class=\"header-middle \">\n");
      out.write("				<div class=\"header-middle-cont\">\n");
      out.write("					<div class=\"toplogo\">\n");
      out.write("						<a href=\"Home.jsp\"> <img src=\"../img/header/logo1.png\"\n");
      out.write("							alt=\"Electronic Store\">\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"shop-menu\">\n");
      out.write("						<ul>\n");
      out.write("							<li class=\"topauth\"><a");
if(user==null){ 
      out.write(" id=btnRegisterHeader");
}else {
								
								
      out.write("\n");
      out.write("							     id=btnCustomer data-idCustomer=\"");
      out.print(customer.getId());
      out.write("\"\n");
      out.write("							     data-nameCustomer=\"");
      out.print(customer.getName());
      out.write("\"\n");
      out.write("							     data-phoneCustomer=\"");
      out.print(customer.getPhone());
      out.write("\"\n");
      out.write("							     data-addressCustomer=\"");
      out.print(customer.getAddress() );
      out.write("\"\n");
      out.write("							     data-emailCustomer=\"");
      out.print(customer.getEmail() );
      out.write("\"\n");
      out.write("							     \n");
      out.write("							      ");
} 
      out.write("> <i\n");
      out.write("									class=\"fas fa-user\"></i> <span class=\"shop-menu-ttl\">");
      out.print(register);
      out.write("</span>\n");
      out.write("							</a> \n");
      out.write("							<a ");
if(user==null){ 
      out.write(" id=\"btnLoginHeader\"");
}else{ 
      out.write("\n");
      out.write("								id=\"btnLogout\"");
} 
      out.write(" \n");
      out.write("								> <span class=\"shop-menu-ttl\">");
      out.print(login);
      out.write("</span>\n");
      out.write("							</a></li>\n");
      out.write("\n");
      out.write("							<li>\n");
      out.write("								<div class=\"h-cart\">\n");
      out.write("									<a href=\"Cart.jsp\"> <i class=\"fa fa-shopping-cart\"></i> <span\n");
      out.write("										class=\"shop-menu-ttl\">Giỏ hàng</span> (<b>");
      out.print(cart.countItem());
      out.write("</b>)\n");
      out.write("									</a>\n");
      out.write("								</div>\n");
      out.write("							</li>\n");
      out.write("\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("	<!-- Logo, Shop-menu - end -->\n");
      out.write("\n");
      out.write("	<!-- Topmenu - start -->\n");
      out.write("	<div class=\"header-bottom\">\n");
      out.write("		<div >\n");
      out.write("			<nav class=\"topmenu\">\n");
      out.write("\n");
      out.write("				<!-- Catalog menu - start -->\n");
      out.write("				<div class=\"topcatalog\">\n");
      out.write("					<a class=\"topcatalog-btn\" ><span>Tất cả</span> Thể Loại</a>\n");
      out.write("					<ul class=\"topcatalog-list\">\n");
      out.write("						");

								List<Category> listCategory = new ArrayList<>();
								listCategory = categoryDAO.listCategory();
								for (int i = 0; i < listCategory.size(); i++) {
									int idCate = listCategory.get(i).getId();
									String nameCate = listCategory.get(i).getName();
							
      out.write("\n");
      out.write("							<li><a\n");
      out.write("								href=\"Category.jsp?cateID=");
      out.print(idCate);
      out.write('"');
      out.write('>');
      out.print(nameCate);
      out.write("</a>\n");
      out.write("								\n");
      out.write("									<ul>\n");
      out.write("									");

											List<Brand> listBrand = new ArrayList<>();
												listBrand = brandDAO.listBrand(i + 1);
												for (int j = 0; j < listBrand.size(); j++) {
													int idBrand = listBrand.get(j).getId();
													String nameBrand = listBrand.get(j).getName();
										
      out.write("\n");
      out.write("								<li><a href=\"Brand.jsp?brandID=");
      out.print(idBrand);
      out.write('"');
      out.write('>');
      out.print(nameBrand);
      out.write("</a></li>\n");
      out.write("									");

											}
										
      out.write("\n");
      out.write("										</ul>\n");
      out.write("										</li>\n");
      out.write("										");

								}
							
      out.write("\n");
      out.write("							</ul>\n");
      out.write("								\n");
      out.write("				</div>\n");
      out.write("				<!-- Catalog menu - end -->\n");
      out.write("\n");
      out.write("				<!-- Main menu - start -->\n");
      out.write("\n");
      out.write("				<ul class=\"mainmenu\">\n");
      out.write("					<li>\n");
      out.write("						<a href=\"index.html\" >\n");
      out.write("							Home\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write("					<li >\n");
      out.write("						<a href=\"#\" >\n");
      out.write("							Product \n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">\n");
      out.write("							Hỗ trợ khách hàng\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\">\n");
      out.write("							Dịch vụ Ưu Đãi\n");
      out.write("						</a>\n");
      out.write("						\n");
      out.write("					</li>\n");
      out.write("					");
if(user!=null){ 
      out.write("\n");
      out.write("					<li>\n");
      out.write("						<a href=\"MyOrder.jsp?idCustomer=");
      out.print(user.getId());
      out.write("\">\n");
      out.write("							Đơn hàng của tôi\n");
      out.write("						</a>\n");
      out.write("						\n");
      out.write("					</li>\n");
      out.write("					");
} 
      out.write("\n");
      out.write("					\n");
      out.write("						\n");
      out.write("				</ul>\n");
      out.write("				<!-- Main menu - end -->\n");
      out.write("\n");
      out.write("				<!-- Search - start -->\n");
      out.write("				<div class=\"topsearch\">\n");
      out.write("				<input id=\"text-Search\" type=\"text\" \n");
      out.write("				");
 
				if(session.getAttribute("textSearch")==null){ 
      out.write(" \n");
      out.write("				placeholder=\"TÌM KIẾM...\"\n");
      out.write("				");
} else { 
					String textSearch= (String) session.getAttribute("textSearch");
				
      out.write("\n");
      out.write("				value=\"");
      out.print(textSearch );
      out.write("\"\n");
      out.write("				\n");
      out.write("				");

				} 
      out.write("\n");
      out.write("				>\n");
      out.write("					<a id=\"btnSearch\" class=\"topsearch-btn\" href=\"#\"><i class=\"fa fa-search\"></i></a>\n");
      out.write("					\n");
      out.write("				</div>\n");
      out.write("				<!-- Search - end -->\n");
      out.write("\n");
      out.write("			</nav>		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Topmenu - end -->\n");
      out.write("<!-- -----Modal--------- -->\n");
      out.write("<div class=\"modal fade\" id=\"LoginModal\" role=\"dialog\" style=\"display: none\">\n");
      out.write("			<div class=\"modal-dialog modal-center\" role=\"document\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=modal-body>\n");
      out.write("							<ul class=\"nav nav-tabs\">\n");
      out.write("								<li><a id=\"loginModalClick\" data-toggle=\"tab\" href=\"#login\">ĐĂNG\n");
      out.write("										NHẬP</a></li>\n");
      out.write("								<li><a id=\"registerModalClick\" data-toggle=\"tab\" href=\"#register\">ĐĂNG KÍ</a></li>\n");
      out.write("							</ul>\n");
      out.write("							<div class=\"tab-content\">\n");
      out.write("								<div id=\"login\" class=\"tab-pane fade in active\">\n");
      out.write("\n");
      out.write("									<h3>Chào mừng tới Shop SmartPhone !</h3>\n");
      out.write("									<div class=\" formLogin\">\n");
      out.write("										<form id=\"form-login\">\n");
      out.write("											<div class=\"form-group\">\n");
      out.write("\n");
      out.write("												<label>E-mail </label> <input\n");
      out.write("													placeholder=\"Vui lòng nhập email của bạn\" type=\"text\"\n");
      out.write("													id=\"textEmail\" class=\"form-control\"> <span\n");
      out.write("													class=\"alert\" id=\"email_alert\"> </span>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("											</div>\n");
      out.write("											\n");
      out.write("											<div class=\"form-group\">\n");
      out.write("												<label>Password </label> <input\n");
      out.write("													placeholder=\"Vui lòng nhập mật khẩu của bạn\"\n");
      out.write("													type=\"password\" id=\"textPassword\" class=\"form-control\">\n");
      out.write("												<span class=\"alert\" id=\"pass_alert\"></span>\n");
      out.write("\n");
      out.write("											</div>\n");
      out.write("											<a id=\"forgot-password\" href=\"#\" style=\"float:left\">Quên mật khẩu?</a>\n");
      out.write("											<div class=\"form-group\">\n");
      out.write("												<button class=\"btn-login\" type=\"button\" id=\"btnLogin\">Đăng\n");
      out.write("													nhập</button>\n");
      out.write("\n");
      out.write("											</div>\n");
      out.write("										</form>\n");
      out.write("										<div class=\"clear-float\"></div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("		<div id=\"register\" class=\"tab-pane fade\">\n");
      out.write("			<h3>Tạo tài khoản ShopSmartPhone</h3>\n");
      out.write("		<div class=\" formLogin\">\n");
      out.write("			<form id=\"form-register\">\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >Họ và tên</label><input type=\"text\" id=\"textNameRegister\" placeholder=\"Vui lòng nhập họ tên của bạn\" class=\"form-control\">\n");
      out.write("					<span class= \"alert\" id= \"name_alertRegister\"></span> \n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >E-mail </label><input type=\"text\" id=\"textEmailRegister\" placeholder=\"Vui lòng nhập email của bạn\" class=\"form-control\" >\n");
      out.write("					<span class= \"alert\" id= \"email_alertRegister\"> </span> \n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >Mật khẩu </label><input id=\"textPasswordRegister\" type=\"password\"  placeholder=\"Vui lòng nhập mật khẩu của bạn\" class=\"form-control\" >\n");
      out.write("					<span class= \"alert\" id= \"pass_alertRegister\"> </span> \n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("				<label >Nhập lại Mật khẩu </label>\n");
      out.write("				<input type=\"password\" id=\"textRePasswordRegister\" placeholder=\"Vui lòng nhập lại mật khẩu của bạn\" class=\"form-control\" >\n");
      out.write("						<span class= \"alert\" id= \"rePass_alertRegister\"> </span> \n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("			<button class=\"btn-login\" type=\"button\" id=\"btnRegister\" >Đăng kí</button>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</form>\n");
      out.write("		<div class=\"clear-float\"></div>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"modal fade\" id=\"forgotModal\" role=\"dialog\" style=\"display: none;top:150px\">\n");
      out.write("		<div class=\"modal-dialog modal-center\" role=\"document\">\n");
      out.write("			<div class=\"modal-content\" style=\"border: 1px solid lightgray;width:80%;margin:auto\">\n");
      out.write("			<div class=\"modal-header\" style=\"    background-color: aliceblue\">\n");
      out.write("						<h3 class=\"modal-title\" style=\"color:black\" >Quên Mật Khẩu</h3>\n");
      out.write("						 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("					<p style=\"font-size:16px\">Nhập tài khoản mà bạn đã quên mật khẩu</p>\n");
      out.write("					<input type=\"text\" style=\"width:100%;border-radius: 5px; border:1px solid lightgray;padding:5px\" \n");
      out.write("					placeholder=\"E-mail\" id=\"emailForgot\" />\n");
      out.write("					<span class=\"alert\" style=\"font-size:15px; padding:20px 0px\" id=\"alert-emailForgot\"></span>\n");
      out.write("					<span class=\"alert\" style=\"font-size:15px; color:green; padding: 20px 0px\" id=\"alert-emailSuccess\"></span>\n");
      out.write("					<div class=modal-footer>\n");
      out.write("					<button data-button=\"forgotPassCustomer\" class=\"btn btn-primary\" id=\"sendForgot\">Gửi</button>\n");
      out.write("					</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div> \n");
      out.write("	<div class=\"modal fade\" id=\"CustomerModal\" role=\"dialog\" style=\"display: none;top: 100px;\">\n");
      out.write("			<div class=\"modal-dialog modal-center\" role=\"document\" >\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=modal-body>\n");
      out.write("						\n");
      out.write("									<div class=\" formLogin\">									\n");
      out.write("									<h2 style=\"text-align:center;margin-bottom:10px; margin-top:10px\">HỒ SƠ KHÁCH HÀNG</h2>\n");
      out.write("									<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >Họ Và Tên</label><input type=\"text\" id=\"textNameCustomer\" placeholder=\"Vui lòng nhập họ tên của bạn\" class=\"form-control\">\n");
      out.write("					<span class= \"alert\" id= \"name_alertCustomer\"></span> \n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >Số Điện Thoại </label><input type=\"text\" id=\"textPhoneCustomer\" placeholder=\"Vui lòng nhập SDT của bạn\" class=\"form-control\">\n");
      out.write("					<span class= \"alert\" id= \"phone_alertCustomer\"></span> \n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >E-mail </label><input type=\"text\" id=\"textEmailCustomer\" readonly placeholder=\"Vui lòng nhập email của bạn\" class=\"form-control\" >\n");
      out.write("					<span class= \"alert\" id= \"email_alertCustomer\" > </span> \n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("				<label >Địa Chỉ </label><input type=\"text\" id=\"textAddressCustomer\" placeholder=\"Vui lòng nhập địa chỉ của bạn\" class=\"form-control\" >\n");
      out.write("					<span class= \"alert\" id= \"address_alertCustomer\"> </span> \n");
      out.write("\n");
      out.write("			</div> \n");
      out.write("			<a id=\"change-password\" href=\"#\" style=\"float:left\">Thay đổi mật khẩu</a>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("			<button data-button=\"editProfileCustomer\" class=\"btn-login\" type=\"button\" id=\"btnEditCustomer\">Chỉnh Sửa</button>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clear-float\"></div>\n");
      out.write("			\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("   </div>\n");
      out.write("   	<div class=\"modal fade\" id=\"changePassword\" role=\"dialog\">\n");
      out.write("		<div class=\"modal-dialog modal-center\" role=\"document\" style=\"top: 100px;\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\" style=\"    background-color: aliceblue;\">\n");
      out.write("					<h3 class=\"modal-title\">Thay đổi mật khẩu</h3>\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\">\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("				<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("					<label>Mật khẩu hiện tại</label>\n");
      out.write("					<input type=\"password\" \n");
      out.write("					id=\"oldpass\" placeholder=\"Nhập mật khẩu hiện tại\">\n");
      out.write("					<span class= \"alert\" id= \"passwordResult\" style=\"padding:0; margin:0\"></span>\n");
      out.write("					</div> \n");
      out.write("						<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("					<label>Mật khẩu mới</label>\n");
      out.write("					<input type=\"password\"  id=\"newpass\" placeholder=\"Nhập mật khẩu mới\">\n");
      out.write("					<span class= \"alert\" id=\"newPasswordResult\"  style=\"padding:0; margin:0\"></span> \n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("					<label>Nhập lại mật khẩu mới</label>\n");
      out.write("					<input type=\"password\" \n");
      out.write("					id=\"renewpass\" placeholder=\"Nhập lại mật khẩu\">\n");
      out.write("						<span class= \"alert\" id= \"repasswordResult\"  style=\"padding:0; margin:0\"> </span> \n");
      out.write("						</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button ");
 if(user!=null){ 
      out.write(" data-id=\"");
      out.print(user.getId() );
 } 
      out.write("\" data-button=\"changePassCustomer\" type=\"button\" id=\"btnChange\" class=\"btn btn-primary\">Đồng Ý</button>\n");
      out.write("					<button id=\"resetChange\" class=\"btn \">Phục Hồi</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"modal fade\" id=\"changeSuccess\" role=\"dialog\">\n");
      out.write("		<div class=\"modal-dialog modal-center\" role=\"document\"  style=\"top: 100px;\">\n");
      out.write("			<div class=\"modal-content\" style=\"border: 1px solid lightgray;width:80%;margin:auto\">\n");
      out.write("				<div class=\"modal-header\" style=\"    background-color: aliceblue;\">\n");
      out.write("					<h3 class=\"modal-title\">Mật Khẩu</h3>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("					<p>Thay đổi mật khẩu thành công!</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" id=\"btnSuccess\" class=\"btn btn-primary\"\n");
      out.write("						data-dismiss=\"modal\">OK</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("					\n");
      out.write("</header>\n");
      out.write("<!-- Header - end -->\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');

	Order order=new Order();
	OrderDAO orderDAO= new OrderDAO();
	List<Order> listOrders= new ArrayList<>();
	DecimalFormat formatter = new DecimalFormat("###,###.00");

      out.write("\n");
      out.write("<section>\n");
      out.write("	");
 
	int count= orderDAO.countOrderDetailByCustomerID(user.getId()); 
	if(count==0){
      out.write("\n");
      out.write("			<div class=\"container\" style=\"text-align: center;font-family: -webkit-body;padding: 130px;\">\n");
      out.write("	 	<h2> Bạn chưa đặt hàng lần nào</h2>\n");
      out.write("		</div>\n");
      out.write("		");
}else{
      out.write("\n");
      out.write("<div class=\"container\" style=\"margin-top:50px\">\n");
      out.write("<ul class=\"nav nav-tabs\">\n");
      out.write("  <li class=\"active\"><a data-toggle=\"tab\" href=\"#home\">ĐƠN HÀNG ĐANG XỬ LÍ</a></li>\n");
      out.write("  <li><a data-toggle=\"tab\" href=\"#menu1\">ĐƠN HÀNG ĐANG GIAO</a></li>\n");
      out.write("    <li><a data-toggle=\"tab\" href=\"#menu2\">ĐƠN HÀNG ĐÃ NHẬN</a></li>\n");
      out.write("</ul>\n");
      out.write(" <div class=\"tab-content\">\n");
      out.write("    <div id=\"home\" class=\"tab-pane fade in active\">\n");
      out.write("   \n");
      out.write("	<div class=\" cart-items-wrap\" style=\"margin: 0 20px\">\n");
      out.write("                <table class=\"cart-items\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"10%\">Mã ĐH</td>\n");
      out.write("                        <td class=\"20%\">Ngày mua Hàng</td>\n");
      out.write("                        <td class=\"20%\">Tổng</td>\n");
      out.write("                        <td class=\"40\">Thông tin người nhận</td>\n");
      out.write("                        <td class=\"10%\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                    ");
if(user!=null){
                    	listOrders= orderDAO.listOrderByCustomer(user.getId(),0);
                    	for (int i=0;i<listOrders.size();i++){
                    		int id=listOrders.get(i).getId();
                    		String date= listOrders.get(i).getCreate_date();
                    		int total= listOrders.get(i).getTotal();
                    		String name= listOrders.get(i).getName();
                    		String phone= listOrders.get(i).getPhone();
                    		String address= listOrders.get(i).getAddress();
                    		String dateReceive= listOrders.get(i).getTime();
                    		
                    	
      out.write("\n");
      out.write("                        <td >\n");
      out.write("                            ");
      out.print(id );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                           ");
      out.print(date );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                       $");
      out.print(formatter.format(total) );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                            \n");
      out.write("                            <ul style=\"list-style: none; padding:0\">\n");
      out.write("                            <li>Tên: ");
      out.print(name );
      out.write("</li>\n");
      out.write("                            <li>SDT: ");
      out.print(phone );
      out.write("</li>\n");
      out.write("                            <li>Địa chỉ: ");
      out.print(address);
      out.write("</li>\n");
      out.write("                            <li>Ngày nhận: ");
      out.print(dateReceive );
      out.write("</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                        <a style=\"color: cornflowerblue;\" href=\"MyOrderDetail.jsp?id=");
      out.print(id);
      out.write("\">Xem chi tiết</a>\n");
      out.write("                        </td>\n");
      out.write("          \n");
      out.write("                    </tr>\n");
      out.write("                    	");
 
                    	}
					} 
					
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            \n");
      out.write("            <div class=\"clear-float\"></div>\n");
      out.write("        </div> \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("<div id=\"menu1\" class=\"tab-pane fade\">\n");
      out.write("  <div class=\" cart-items-wrap\" style=\"margin: 0 20px\">\n");
      out.write("                <table class=\"cart-items\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"10%\">Mã ĐH</td>\n");
      out.write("                        <td class=\"20%\">Ngày mua Hàng</td>\n");
      out.write("                        <td class=\"20%\">Tổng</td>\n");
      out.write("                        <td class=\"40\">Thông tin người nhận</td>\n");
      out.write("                        <td class=\"10%\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                    ");
if(user!=null){
                    	listOrders= orderDAO.listOrderByCustomer(user.getId(),1);
                    	for (int i=0;i<listOrders.size();i++){
                    		int id=listOrders.get(i).getId();
                    		String date= listOrders.get(i).getCreate_date();
                    		int total= listOrders.get(i).getTotal();
                    		String name= listOrders.get(i).getName();
                    		String phone= listOrders.get(i).getPhone();
                    		String address= listOrders.get(i).getAddress();
                    		String dateReceive= listOrders.get(i).getTime();
                    		
                    	
      out.write("\n");
      out.write("                        <td >\n");
      out.write("                            ");
      out.print(id );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                           ");
      out.print(date );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                       $");
      out.print(formatter.format(total) );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                            \n");
      out.write("                            <ul style=\"list-style: none; padding:0\">\n");
      out.write("                            <li>Tên: ");
      out.print(name );
      out.write("</li>\n");
      out.write("                            <li>SDT: ");
      out.print(phone );
      out.write("</li>\n");
      out.write("                            <li>Địa chỉ: ");
      out.print(address);
      out.write("</li>\n");
      out.write("                            <li>Ngày nhận: ");
      out.print(dateReceive );
      out.write("</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                        <a style=\"color: cornflowerblue;\" href=\"MyOrderDetail.jsp?id=");
      out.print(id);
      out.write("\">Xem chi tiết</a>\n");
      out.write("                        </td>\n");
      out.write("          \n");
      out.write("                    </tr>\n");
      out.write("                    	");
 
                    	}
					} 
					
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            \n");
      out.write("            <div class=\"clear-float\"></div>\n");
      out.write("        </div> \n");
      out.write("  </div>\n");
      out.write("  <div id=\"menu2\" class=\"tab-pane fade\">\n");
      out.write("  <div class=\" cart-items-wrap\" style=\"margin: 0 20px\">\n");
      out.write("                <table class=\"cart-items\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"10%\">Mã ĐH</td>\n");
      out.write("                        <td class=\"20%\">Ngày mua Hàng</td>\n");
      out.write("                        <td class=\"20%\">Tổng</td>\n");
      out.write("                        <td class=\"40\">Thông tin người nhận</td>\n");
      out.write("                        <td class=\"10%\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                    ");
if(user!=null){
                    	listOrders= orderDAO.listOrderByCustomer(user.getId(),2);
                    	for (int i=0;i<listOrders.size();i++){
                    		int id=listOrders.get(i).getId();
                    		String date= listOrders.get(i).getCreate_date();
                    		int total= listOrders.get(i).getTotal();
                    		String name= listOrders.get(i).getName();
                    		String phone= listOrders.get(i).getPhone();
                    		String address= listOrders.get(i).getAddress();
                    		String dateReceive= listOrders.get(i).getTime();
                    		
                    	
      out.write("\n");
      out.write("                        <td >\n");
      out.write("                            ");
      out.print(id );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                           ");
      out.print(date );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                       $");
      out.print(formatter.format(total) );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td >\n");
      out.write("                            \n");
      out.write("                            <ul style=\"list-style: none; padding:0\">\n");
      out.write("                            <li>Tên: ");
      out.print(name );
      out.write("</li>\n");
      out.write("                            <li>SDT: ");
      out.print(phone );
      out.write("</li>\n");
      out.write("                            <li>Địa chỉ: ");
      out.print(address);
      out.write("</li>\n");
      out.write("                            <li>Ngày nhận: ");
      out.print(dateReceive );
      out.write("</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                        <a style=\"color: cornflowerblue;\" href=\"MyOrderDetail.jsp?id=");
      out.print(id);
      out.write("\">Xem chi tiết</a>\n");
      out.write("                        </td>\n");
      out.write("          \n");
      out.write("                    </tr>\n");
      out.write("                    	");
 
                    	}
					} 
					
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            \n");
      out.write("            <div class=\"clear-float\"></div>\n");
      out.write("        </div> \n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
} 

      out.write("\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- Footer - start -->\n");
      out.write("<footer class=\"footer-wrap\">\n");
      out.write("    <div class=\"container f-menu-list\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("                <h3>\n");
      out.write("                   Hỗ trợ khách hàng\n");
      out.write("                </h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>Monday-Sunday(9am-6pm)</li>\n");
      out.write("                    <li>Hotline đặt hàng: <span style=\"color:red; font-size:15px\">1800-1800</span></li>\n");
      out.write("                    <li>Hỗ trợ : <a href=\"#\">support@smart.vn</a></li>\n");
      out.write("                    <li>Bảo mật : <a href=\"#\">security@smart.vn</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("                <h3>\n");
      out.write("                   Về ShopSmartPhone\n");
      out.write("                </h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">Giới thiệu về Shop Smartphone</a></li>\n");
      out.write("                    <li><a href=\"#\">Chính sách bảo mật</a></li>\n");
      out.write("                    <li><a href=\"#\">Điều khoản sử dụng</a></li>\n");
      out.write("                    <li><a href=\"#\">Tuyển dụng</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("                <h3>\n");
      out.write("                    Phương thức thanh toán\n");
      out.write("                </h3>\n");
      out.write("                <div>\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/005-visa.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/006-jcb.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/007-atm.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/008-mastercard.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/009-money.png\" alt=\"\">\n");
      out.write("                 \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("            <h3>Ứng dụng trên điện thoại</h3>\n");
      out.write("             <img style=\"width:150px; height:auto\" src=\"../img/header/chplay.png\" alt=\"\">\n");
      out.write("             <img style=\"width:150px; height:auto\" src=\"../img/header/ios.png\" alt=\"\">\n");
      out.write("                       \n");
      out.write("            </div>\n");
      out.write("       \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\" footer-bottom\">\n");
      out.write("    	<div class=\"row \">\n");
      out.write("                <ul class=\" container social-icons\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://facebook.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-facebook\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://google.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-google-plus\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://twitter.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://vk.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-vk\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://instagram.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-instagram\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</footer>\n");
      out.write("<!-- Footer - end -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
