/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-27 14:18:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.project.ecommerce.model.Employee;
import com.project.ecommerce.dao.BrandDAO;
import com.project.ecommerce.model.Brand;
import com.project.ecommerce.dao.CategoryDAO;
import com.project.ecommerce.model.Category;
import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;

public final class BrandAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Admin/../CssAdmin/fstyle.css", Long.valueOf(1699944475685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.project.ecommerce.model.Employee");
    _jspx_imports_classes.add("com.project.ecommerce.dao.BrandDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Category");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.project.ecommerce.model.Brand");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CategoryDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"../Js/jquery.twbsPagination.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>");
      out.write("@charset \"UTF-8\";\n");
      out.write("\n");
      out.write("header {\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content h3 {\n");
      out.write("	float: left;\n");
      out.write("	margin: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 {\n");
      out.write("	float: right;\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li {\n");
      out.write("	list-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li a {\n");
      out.write("	color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li a:hover {\n");
      out.write("	cursor: pointer;\n");
      out.write("	background-color: #EEEEEE;\n");
      out.write("	color: blue;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown:hover .dropdown-content {\n");
      out.write("	display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content {\n");
      out.write("	position: absolute;\n");
      out.write("	background-color: white;\n");
      out.write("	z-index: 1;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul {\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li {\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background-color: white;\n");
      out.write("	width: 140%;\n");
      out.write("	float: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li a {\n");
      out.write("	font-size: 14px;\n");
      out.write("	padding: 14px;\n");
      out.write("	display: block;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li a i {\n");
      out.write("	margin-right: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sub-dropdown {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".clear-float {\n");
      out.write("	clear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section {\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu {\n");
      out.write("	padding: 0px;\n");
      out.write("	border-right: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content {\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .layout {\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul {\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li {\n");
      out.write("	list-style: none;\n");
      out.write("	padding: 10px;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li:hover {\n");
      out.write("	background-color: #EEEEEE;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li a {\n");
      out.write("	padding-left: 10px;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li a i {\n");
      out.write("	margin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content {\n");
      out.write("	background-color: white;\n");
      out.write("	padding: 30px 30px 20px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .Title-view {\n");
      out.write("	float: left;\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Title-add {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Title-edit {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo {\n");
      out.write("	float: right;\n");
      out.write("	padding: 5px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo input {\n");
      out.write("	float: left;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-bottom-left-radius: 5px;\n");
      out.write("	padding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo button {\n");
      out.write("	padding: 5px 10px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("	border-bottom-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .content-page {\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .content-page .head-table {\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("	text-align: left;\n");
      out.write("	padding: 10px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("	border-bottom: 0;\n");
      out.write("	margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content-table {\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	padding: 10px;\n");
      out.write("	width: 100%;\n");
      out.write("	padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view th {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	border-top: 0;\n");
      out.write("	border-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view td {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	border-top: 0;\n");
      out.write("	border-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .table-head {\n");
      out.write("	margin-top: 20px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background: #F8F8F8;\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-head p {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".table-content {\n");
      out.write("	padding-top: 10px;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-left: 1px lightgray solid;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("	border-right: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content input, select{\n");
      out.write("	padding: 0 5px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write(".table-content textarea {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content h6 {\n");
      out.write("	margin-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add td {\n");
      out.write("	padding: 10px 10px 0 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add input {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	width: 70%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add textarea {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	width: 70%;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add .button-control {\n");
      out.write("	padding: 10px 10px 20px 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add .button-control button {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 0px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	color: white;\n");
      out.write("	background-color: #00CC33;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".alert {\n");
      out.write("	color: red;\n");
      out.write("	font-size: 12px;\n");
      out.write("	font-weight: 400;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add p {\n");
      out.write("	margin: 0;\n");
      out.write("	border: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content p {\n");
      out.write("	margin: 0;\n");
      out.write("	border: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background-color: #F5F5F5;\n");
      out.write("	/* width: 100%; */\n");
      out.write("	height: 100%;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	width: 100%;\n");
      out.write("	margin: auto;\n");
      out.write("	padding-bottom: 30px;\n");
      out.write("	padding-top: 5%;\n");
      out.write("	background: #F8F8F8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".label {\n");
      out.write("	height: 10%;\n");
      out.write("	width: 36%;\n");
      out.write("	margin: auto;\n");
      out.write("	background: #F5F5F5;\n");
      out.write("	border-radius: 5px 5px 0 0;\n");
      out.write("	border: 2px solid #DDDDDD;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".label p {\n");
      out.write("	margin-left: 5%;\n");
      out.write("	font-size: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".remember {\n");
      out.write("	margin-left: 6%;\n");
      out.write("	margin-bottom: 5%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal .modal-dialog{\n");
      out.write("	width: 100%;\n");
      out.write("    margin: auto;\n");
      out.write("    top: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* .content-table .td-update button{\n");
      out.write("	padding: 5px;\n");
      out.write("    border: 0px;\n");
      out.write("    width:60px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    color: white;\n");
      out.write("    background-color: #007bff;\n");
      out.write("} */\n");
      out.write(".modal-header{\n");
      out.write("	background-color:cadetblue; \n");
      out.write("	color:white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#pagination {\n");
      out.write("		display: flex;\n");
      out.write("		display: -webkit-flex; /* Safari 8 */\n");
      out.write("		flex-wrap: wrap;\n");
      out.write("		-webkit-flex-wrap: wrap; /* Safari 8 */\n");
      out.write("		justify-content: center;\n");
      out.write("		-webkit-justify-content: center;\n");
      out.write("	}\n");
      out.write("/* ---------abc-------- */\n");
      out.write(".modal-title{\n");
      out.write("	font-size:20px;\n");
      out.write("}\n");
      out.write(".modal-body, .modal-body h6 {\n");
      out.write("	font-size:16px;\n");
      out.write("}\n");
      out.write(".modal-body input{\n");
      out.write("	width: 100%;\n");
      out.write("    height: 30px;\n");
      out.write("    border: 1px solid lightgray;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("}\n");
      out.write(".modal-body select{\n");
      out.write("	width:100%;\n");
      out.write("	height:30px;\n");
      out.write("	margin:0;\n");
      out.write("	 border: 1px solid lightgray;\n");
      out.write("    border-radius: 5px;\n");
      out.write("}\n");
      out.write(".btn-addcontent{\n");
      out.write("	position: absolute;\n");
      out.write("	    top: 37px;\n");
      out.write("    right: 400px;\n");
      out.write("}\n");
      out.write(" .table-content h6,\n");
      out.write(".table-content h5{\n");
      out.write("	font-size:16px;\n");
      out.write("	margin-left:15px;\n");
      out.write("}\n");
      out.write(".table-content input{\n");
      out.write("	height:30px;\n");
      out.write("}");
      out.write("</style> \n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Category</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>	 ");

		Employee user = (Employee) session.getAttribute("employeeSession");
		 if(user == null){			
			response.sendRedirect("LoginAdmin.jsp");
			return;
		} 
		
      out.write(" \n");
      out.write("\n");
      out.write("	");

	Brand brand = new Brand();
	BrandDAO brandDAO= new BrandDAO();
	List<Brand> listBrands= new ArrayList<>();
	listBrands= brandDAO.listAllBrand();
	CategoryDAO categoryDAO= new CategoryDAO();
	Category category= new Category();
	List<Category> lisCategories= new ArrayList<>();
		
		
	
      out.write("\n");
      out.write("	<h2 style= \"margin-right: 500px;\" class=\"Title-view\">Hãng</h2>\n");
      out.write("	<button class=\"btn-addcontent btn btn-primary\">Thêm Hãng</button>\n");
      out.write("	<div class=\"search-ifo\">\n");
      out.write("		<input id=\"text-Search\" placeholder=\"Search...\">\n");
      out.write("		<button id=\"btn-Search\">\n");
      out.write("			<i class=\"fas fa-search\"></i>\n");
      out.write("		</button>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"clear-float\"></div>\n");
      out.write("	<hr style=\"margin-top: 0px;\">\n");
      out.write("	<div class=\"content-page\">\n");
      out.write("\n");
      out.write("		<p class=\"head-table\">Danh sách Hãng</p>\n");
      out.write("\n");
      out.write("		<div style=\"height: 480px\" class=\"content-table table-responsive\">\n");
      out.write("				<table class=\"table table-striped edit-table-view\" >\n");
      out.write("			\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"width: 15%\">Mã Hãng</th>\n");
      out.write("						<th style=\"width: 50%\">Tên Hãng</th>\n");
      out.write("						<th style=\"width: 25%\">Thể Loại</th>\n");
      out.write("						<th style=\"width: 5%\"></th>\n");
      out.write("						<th style=\"width: 5%\"></th>\n");
      out.write("						</tr>\n");
      out.write("				 	");

					  for (int i = 0; i < listBrands.size(); i++) {  
							 category= categoryDAO.categoryById(listBrands.get(i).getIdcategory());
					
					
      out.write(" \n");
      out.write("					<tr style=\"height:50px\" class=\"contentPage tableViewContent\" >\n");
      out.write("					\n");
      out.write("						<td >");
      out.print(listBrands.get(i).getId() );
      out.write("</td>\n");
      out.write("						<td class=\"colName\">");
      out.print(listBrands.get(i).getName());
      out.write("</td>\n");
      out.write("						<td class=\"colCategory\">");
      out.print(category.getName());
      out.write("</td>\n");
      out.write("						<td>\n");
      out.write("						<button id=\"btn-delete\" class=\"btn btn-delete\"\n");
      out.write("						");
 int count=brandDAO.countBrandinProduct(listBrands.get(i).getId());
							if(count>0){
						
      out.write("	style=\"display:none\"\n");
      out.write("						");
} 
      out.write("\n");
      out.write("						\n");
      out.write("								data-name=\"");
      out.print(listBrands.get(i).getName());
      out.write("\"\n");
      out.write("								data-id=\"");
      out.print(listBrands.get(i).getId());
      out.write("\">Xóa</button>\n");
      out.write("							\n");
      out.write("						</td>\n");
      out.write("						<td>\n");
      out.write("						<button id=\"btn-edit");
      out.print(listBrands.get(i).getId());
      out.write("\" class=\"btn btn-primary btn-edit\"\n");
      out.write("								data-id=\"");
      out.print(listBrands.get(i).getId());
      out.write("\"\n");
      out.write("								data-name=\"");
      out.print(listBrands.get(i).getName());
      out.write("\"\n");
      out.write("								data-cateID=\"");
      out.print(listBrands.get(i).getIdcategory() );
      out.write("\"\n");
      out.write("						>Sửa</button>\n");
      out.write("						</td>\n");
      out.write("						\n");
      out.write("\n");
      out.write("					</tr>\n");
      out.write("				\n");
      out.write("				");

					}
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<ul style=\"margin-top: 20px\" id=\"pagination\" class=\"justify-content-center\">\n");
      out.write("	  	</ul>\n");
      out.write("	  	\n");
      out.write("		<div class=\"modal fade\" id=\"deleteModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" style=\"display: none\">\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Xóa Hãng</h5>\n");
      out.write("						 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("					<span>Bạn có muốn xóa hãng : </span><span id=\"alertDelete\"></span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("				<p class=\"alert\" id=\"alertNoDelete\" style=\"margin: 0; padding: 0;\"></p>\n");
      out.write("				</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("							data-button=\"delete\" id=\"delete\">Có</button>\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Không</button>\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"modal fade\" id=\"editPostModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" >\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<form class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Sửa Hãng</h5>\n");
      out.write("						 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<h6 >\n");
      out.write("							Tên Hãng\n");
      out.write("							\n");
      out.write("						</h6>\n");
      out.write("					\n");
      out.write("						\n");
      out.write("						<input type=\"text\"  id=\"edit-name\" style=\"width: 100%\" />\n");
      out.write("						<p class=\"alert\" id = \"alert_name\" style=\"margin: 0; padding: 0;\"> </p>	\n");
      out.write("						</div>\n");
      out.write("							<div class=\"modal-footer\">			\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" id=\"edit\" data-\n");
      out.write("								 data-button=\"edit\">Đồng Ý</button>\n");
      out.write("						<button type=\"button\" id=\"reset-edit\" class=\"btn btn-default\">Phục Hồi</button>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"modal fade\" id=\"addViewContentModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" >\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<form class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Thêm Hãng</h5>\n");
      out.write("						 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<h6 >\n");
      out.write("							Tên Hãng\n");
      out.write("							\n");
      out.write("						</h6>\n");
      out.write("					\n");
      out.write("						\n");
      out.write("						<input type=\"text\"  id=\"text-name\" style=\"width: 100%\" />\n");
      out.write("						<p class=\"alert\" id = \"alertadd_name\" style=\"margin: 0; padding: 0;\"> </p>\n");
      out.write("						<p>Thể Loại</p>\n");
      out.write("						<select id=\"cmbCategories\"> \n");
      out.write("						");
 
							lisCategories= categoryDAO.listCategory();
							for(int i=0;i<lisCategories.size();i++){
							
      out.write("\n");
      out.write(" 							 <option value=\"");
      out.print(lisCategories.get(i).getId());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(lisCategories.get(i).getName());
      out.write("</option>\n");
      out.write("  							");

							}
  							
      out.write("\n");
      out.write("						</select>	\n");
      out.write("						</div>\n");
      out.write("							<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" id=\"add\"\n");
      out.write("								 data-button=\"add\">Đồng Ý</button>\n");
      out.write("							<button type=\"reset\" id=\"reset-add\" class=\"btn btn-default\">Phục Hồi </button>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("	$(document).ready(function() {\n");
      out.write("		var id = $(this).attr(\"data-id\")\n");
      out.write("		var name = $(this).attr(\"data-name\")\n");
      out.write("\n");
      out.write("		//bắt sự kiện click nút delete trong table \n");
      out.write("		$(\".btn-delete\").click(function() {\n");
      out.write("			\n");
      out.write("			var id = $(this).attr(\"data-id\")\n");
      out.write("			var name = $(this).attr(\"data-name\")\n");
      out.write("			$('#delete').val(id);\n");
      out.write("			t = $(this).parent().parent('tr');\n");
      out.write("			$('#alertDelete').html(name)\n");
      out.write("			$(\"#deleteModal\").modal('show')\n");
      out.write("		})\n");
      out.write("		$(\"#delete\").click(function() {\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			var id = $('#delete').val();\n");
      out.write("			var dataButton = $(this).attr('data-button');\n");
      out.write("			$.ajax({\n");
      out.write("				type : \"post\",\n");
      out.write("				url : \"/ShopSmartPhone/brandServlet\",\n");
      out.write("				data : {\n");
      out.write("					id : id,\n");
      out.write("					dataButton : dataButton\n");
      out.write("				},\n");
      out.write("				success : function(response) {\n");
      out.write("					if (response == \"success\") {\n");
      out.write("						$(\"#deleteModal\").modal('hide')\n");
      out.write("					/* 	$(\"#content\").load(\"ManagerPost.jsp\") */\n");
      out.write("						$('.modal-backdrop').remove()\n");
      out.write("						t.remove();\n");
      out.write("					}\n");
      out.write("					\n");
      out.write("					else if(response == \"fail\"){\n");
      out.write("						$('#alertNoDelete').html('(* Đã có lỗi xảy ra *)')\n");
      out.write("					}\n");
      out.write("					else if(response == \"exist\"){\n");
      out.write("						$('#alertNoDelete').html('(* Không thể xóa vì đã có sản phẩm *)')\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		//bắt sự kiện click nút Add trong table \n");
      out.write("		$(\".btn-addcontent\").click(function() {\n");
      out.write("			$(\"#addViewContentModal\").modal('show')\n");
      out.write("			\n");
      out.write("			$(\"#text-name\").keypress(function() {\n");
      out.write("				$(\"#alertadd_name\").html('')\n");
      out.write("			})\n");
      out.write("		})\n");
      out.write("		$(\"#add\").click(function() {\n");
      out.write("			var name = $('#text-name').val()\n");
      out.write("			var dataButton = $(this).attr('data-button')\n");
      out.write("			var idCate= $('#cmbCategories').val()\n");
      out.write("			console.log(idCate)\n");
      out.write("			var flag = 0;\n");
      out.write("			if(name.trim()==\"\"){\n");
      out.write("            	$(\"#alertadd_name\").html('(* Bạn cần điền tên hãng *)')\n");
      out.write("            	flag=1;\n");
      out.write("            }\n");
      out.write("	        if(flag == 0){\n");
      out.write("			$.ajax({\n");
      out.write("				type : \"post\",\n");
      out.write("				url : \"/ShopSmartPhone/brandServlet\",\n");
      out.write("				data:{\n");
      out.write("					name : name,\n");
      out.write("					idCate : idCate,\n");
      out.write("					dataButton: dataButton\n");
      out.write("				},\n");
      out.write("				success : function(response) {\n");
      out.write("					if (response == \"success\") {\n");
      out.write("						$(\"#addViewContentModal\").modal('hide')						\n");
      out.write("						$('.modal-backdrop').remove() \n");
      out.write("						$(\"#content\").load(\"../Admin/BrandAdmin.jsp\")\n");
      out.write("					}\n");
      out.write("					else if(response == \"exist\"){\n");
      out.write("						$(\"#alertadd_name\").html('(* Đã tồn tại tên hãng này với thể loại này *)')\n");
      out.write("					}\n");
      out.write("					else if(response == \"fail\"){\n");
      out.write("						$(\"#alertadd_name\").html('(* Đã có lỗi xảy ra *)')\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("	       }\n");
      out.write("	    	\n");
      out.write("		})\n");
      out.write("		//bắt sự kiện click nút Edit trong table \n");
      out.write("		$(\".btn-edit\").click(function() {\n");
      out.write("			$(\"#editPostModal\").modal('show')\n");
      out.write("			t = $(this).parent().parent('tr');\n");
      out.write("			var id = $(this).attr(\"data-id\")\n");
      out.write("			var name = $(this).attr(\"data-name\")\n");
      out.write("			\n");
      out.write("		    var idCate = $(this).attr(\"data-cateID\")\n");
      out.write("			$(\"#reset-edit\").click(function(){\n");
      out.write("				$('#edit-name').val(name)\n");
      out.write("			})\n");
      out.write("			$('#reset-edit').val(idCate)\n");
      out.write("			$('#edit').val(id)\n");
      out.write("			$('#edit-name').val(name)\n");
      out.write("\n");
      out.write("			$(\"#edit-name\").keypress(function() {\n");
      out.write("				$(\"#alert_name\").html('')\n");
      out.write("			})\n");
      out.write("\n");
      out.write("		})\n");
      out.write("		//bắt sự kiện click OK\n");
      out.write("		$(\"#edit\").click(function() {\n");
      out.write("			var id = $('#edit').val()\n");
      out.write("			var name = $('#edit-name').val()\n");
      out.write("			var idCate= $('#reset-edit').val()\n");
      out.write("			console.log(idCate)\n");
      out.write("			var dataButton = $(this).attr('data-button')\n");
      out.write("			var flag = 0;\n");
      out.write("			var idedit= \"#btn-edit\"+id\n");
      out.write("			 if(name.trim()==\"\"){\n");
      out.write("	            	$(\"#alert_name\").html('(* Bạn cần điền tên hãng *)')\n");
      out.write("	            	flag = 1;\n");
      out.write("	            }\n");
      out.write("\n");
      out.write("	        if(flag == 0){\n");
      out.write("			$.ajax({\n");
      out.write("				type : \"post\",\n");
      out.write("				url : \"/ShopSmartPhone/brandServlet\",\n");
      out.write("				data : {\n");
      out.write("					id : id,\n");
      out.write("					name : name,\n");
      out.write("					idCate : idCate,\n");
      out.write("					dataButton : dataButton\n");
      out.write("				},\n");
      out.write("				success : function(response) {\n");
      out.write("					if (response == \"success\") {\n");
      out.write("						$(\"#editPostModal\").modal('hide')\n");
      out.write("						$('.modal-backdrop').remove()  \n");
      out.write("						t.find('.colName').html(name)\n");
      out.write("						$(idedit).attr('data-name',name)\n");
      out.write("					}\n");
      out.write("					else if(response == \"exist\"){\n");
      out.write("						$(\"#alert_name\").html('(* Đã tồn tại hãng này *)')\n");
      out.write("					}\n");
      out.write("					else if(response == \"fail\"){\n");
      out.write("						$(\"#alert_name\").html('(* Đã có lỗi xảy ra *)')\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("	       }\n");
      out.write("	    	\n");
      out.write("		})\n");
      out.write("\n");
      out.write("		//hàm chuyển các giá trị trong col thành chữ thường LowerCase()\n");
      out.write("		$.extend($.expr[\":\"], {\"containsNC\": function(elem, i, match, array) {\n");
      out.write("        return (elem.textContent || elem.innerText || \"\").toLowerCase().indexOf((match[3] || \"\").toLowerCase()) >= 0;\n");
      out.write("			}\n");
      out.write("			});\n");
      out.write("		//bắt sự kiện search, giá trị nhập vào thành chữ thường \n");
      out.write("		$(\"#btn-Search\").click(function() {\n");
      out.write("			var a = $(\"#text-Search\").val().toLowerCase();\n");
      out.write("			    $(\".tableViewContent td.colName:containsNC('\" +a + \"')\").parent().show();\n");
      out.write("		        $(\".tableViewContent td.colName:not(:containsNC('\" +a+ \"'))\").parent().hide();\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("		$(function () {	\n");
      out.write("		var pageSize = 6; // Hiển thị 6 sản phẩm trên 1 trang\n");
      out.write("		showPage = function(page) {\n");
      out.write("			$(\".contentPage\").hide();\n");
      out.write("			$(\".contentPage\").each(function(n) {\n");
      out.write("				if (n >= pageSize * (page - 1) && n < pageSize * page)\n");
      out.write("					$(this).show();\n");
      out.write("			});        \n");
      out.write("		}\n");
      out.write("		showPage(1);\n");
      out.write("		///** Cần truyền giá trị vào đây **///\n");
      out.write("		var totalRows = ");
      out.print(listBrands.size());
      out.write("; // Tổng số sản phẩm hiển thị\n");
      out.write("		var btnPage = Math.ceil(");
      out.print(listBrands.size());
      out.write("/pageSize); ; // Số nút bấm hiển thị di chuyển trang\n");
      out.write("		var iTotalPages = Math.ceil(totalRows / pageSize);\n");
      out.write("\n");
      out.write("		var obj = $('#pagination').twbsPagination({\n");
      out.write("			totalPages: iTotalPages,\n");
      out.write("			visiblePages: btnPage,\n");
      out.write("			onPageClick: function (event, page) {\n");
      out.write("				/* console.info(page); */\n");
      out.write("				showPage(page);\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
