/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-27 14:20:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import com.project.ecommerce.dao.CustomerDAO;
import com.project.ecommerce.model.Customer;
import com.project.ecommerce.dao.EmployeeDAO;
import com.project.ecommerce.model.Employee;
import com.project.ecommerce.dao.OrderDAO;
import com.project.ecommerce.model.Order;
import com.project.ecommerce.dao.BrandDAO;
import com.project.ecommerce.model.Brand;
import com.project.ecommerce.dao.CategoryDAO;
import com.project.ecommerce.model.Category;
import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;

public final class OrderAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Admin/../CssAdmin/fstyle.css", Long.valueOf(1699944475685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.ecommerce.dao.BrandDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Category");
    _jspx_imports_classes.add("com.project.ecommerce.model.Customer");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.project.ecommerce.model.Brand");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CategoryDAO");
    _jspx_imports_classes.add("com.project.ecommerce.dao.EmployeeDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CustomerDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Employee");
    _jspx_imports_classes.add("com.project.ecommerce.model.Order");
    _jspx_imports_classes.add("com.project.ecommerce.dao.OrderDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"../Js/jquery.twbsPagination.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>");
      out.write("@charset \"UTF-8\";\n");
      out.write("\n");
      out.write("header {\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content h3 {\n");
      out.write("	float: left;\n");
      out.write("	margin: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 {\n");
      out.write("	float: right;\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li {\n");
      out.write("	list-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li a {\n");
      out.write("	color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li a:hover {\n");
      out.write("	cursor: pointer;\n");
      out.write("	background-color: #EEEEEE;\n");
      out.write("	color: blue;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown:hover .dropdown-content {\n");
      out.write("	display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content {\n");
      out.write("	position: absolute;\n");
      out.write("	background-color: white;\n");
      out.write("	z-index: 1;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul {\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li {\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background-color: white;\n");
      out.write("	width: 140%;\n");
      out.write("	float: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li a {\n");
      out.write("	font-size: 14px;\n");
      out.write("	padding: 14px;\n");
      out.write("	display: block;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li a i {\n");
      out.write("	margin-right: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sub-dropdown {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".clear-float {\n");
      out.write("	clear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section {\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu {\n");
      out.write("	padding: 0px;\n");
      out.write("	border-right: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content {\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .layout {\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul {\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li {\n");
      out.write("	list-style: none;\n");
      out.write("	padding: 10px;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li:hover {\n");
      out.write("	background-color: #EEEEEE;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li a {\n");
      out.write("	padding-left: 10px;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li a i {\n");
      out.write("	margin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content {\n");
      out.write("	background-color: white;\n");
      out.write("	padding: 30px 30px 20px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .Title-view {\n");
      out.write("	float: left;\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Title-add {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Title-edit {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo {\n");
      out.write("	float: right;\n");
      out.write("	padding: 5px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo input {\n");
      out.write("	float: left;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-bottom-left-radius: 5px;\n");
      out.write("	padding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo button {\n");
      out.write("	padding: 5px 10px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("	border-bottom-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .content-page {\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .content-page .head-table {\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("	text-align: left;\n");
      out.write("	padding: 10px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("	border-bottom: 0;\n");
      out.write("	margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content-table {\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	padding: 10px;\n");
      out.write("	width: 100%;\n");
      out.write("	padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view th {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	border-top: 0;\n");
      out.write("	border-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view td {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	border-top: 0;\n");
      out.write("	border-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .table-head {\n");
      out.write("	margin-top: 20px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background: #F8F8F8;\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-head p {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".table-content {\n");
      out.write("	padding-top: 10px;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-left: 1px lightgray solid;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("	border-right: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content input, select{\n");
      out.write("	padding: 0 5px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write(".table-content textarea {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content h6 {\n");
      out.write("	margin-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add td {\n");
      out.write("	padding: 10px 10px 0 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add input {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	width: 70%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add textarea {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	width: 70%;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add .button-control {\n");
      out.write("	padding: 10px 10px 20px 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add .button-control button {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 0px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	color: white;\n");
      out.write("	background-color: #00CC33;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".alert {\n");
      out.write("	color: red;\n");
      out.write("	font-size: 12px;\n");
      out.write("	font-weight: 400;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add p {\n");
      out.write("	margin: 0;\n");
      out.write("	border: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content p {\n");
      out.write("	margin: 0;\n");
      out.write("	border: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background-color: #F5F5F5;\n");
      out.write("	/* width: 100%; */\n");
      out.write("	height: 100%;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	width: 100%;\n");
      out.write("	margin: auto;\n");
      out.write("	padding-bottom: 30px;\n");
      out.write("	padding-top: 5%;\n");
      out.write("	background: #F8F8F8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".label {\n");
      out.write("	height: 10%;\n");
      out.write("	width: 36%;\n");
      out.write("	margin: auto;\n");
      out.write("	background: #F5F5F5;\n");
      out.write("	border-radius: 5px 5px 0 0;\n");
      out.write("	border: 2px solid #DDDDDD;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".label p {\n");
      out.write("	margin-left: 5%;\n");
      out.write("	font-size: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".remember {\n");
      out.write("	margin-left: 6%;\n");
      out.write("	margin-bottom: 5%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal .modal-dialog{\n");
      out.write("	width: 100%;\n");
      out.write("    margin: auto;\n");
      out.write("    top: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* .content-table .td-update button{\n");
      out.write("	padding: 5px;\n");
      out.write("    border: 0px;\n");
      out.write("    width:60px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    color: white;\n");
      out.write("    background-color: #007bff;\n");
      out.write("} */\n");
      out.write(".modal-header{\n");
      out.write("	background-color:cadetblue; \n");
      out.write("	color:white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#pagination {\n");
      out.write("		display: flex;\n");
      out.write("		display: -webkit-flex; /* Safari 8 */\n");
      out.write("		flex-wrap: wrap;\n");
      out.write("		-webkit-flex-wrap: wrap; /* Safari 8 */\n");
      out.write("		justify-content: center;\n");
      out.write("		-webkit-justify-content: center;\n");
      out.write("	}\n");
      out.write("/* ---------abc-------- */\n");
      out.write(".modal-title{\n");
      out.write("	font-size:20px;\n");
      out.write("}\n");
      out.write(".modal-body, .modal-body h6 {\n");
      out.write("	font-size:16px;\n");
      out.write("}\n");
      out.write(".modal-body input{\n");
      out.write("	width: 100%;\n");
      out.write("    height: 30px;\n");
      out.write("    border: 1px solid lightgray;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("}\n");
      out.write(".modal-body select{\n");
      out.write("	width:100%;\n");
      out.write("	height:30px;\n");
      out.write("	margin:0;\n");
      out.write("	 border: 1px solid lightgray;\n");
      out.write("    border-radius: 5px;\n");
      out.write("}\n");
      out.write(".btn-addcontent{\n");
      out.write("	position: absolute;\n");
      out.write("	    top: 37px;\n");
      out.write("    right: 400px;\n");
      out.write("}\n");
      out.write(" .table-content h6,\n");
      out.write(".table-content h5{\n");
      out.write("	font-size:16px;\n");
      out.write("	margin-left:15px;\n");
      out.write("}\n");
      out.write(".table-content input{\n");
      out.write("	height:30px;\n");
      out.write("}");
      out.write("</style> \n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Category</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	 ");

		Employee user = (Employee) session.getAttribute("employeeSession");
		 if(user == null){			
			response.sendRedirect("LoginAdmin.jsp");
			return;
		} 
	Order order=new Order();
	OrderDAO orderDAO= new OrderDAO();
	List<Order> listOrders= new ArrayList<>();
	Employee employee= new Employee();
	EmployeeDAO employeeDAO= new EmployeeDAO();
	Customer customer= new Customer();
	CustomerDAO customerDAO= new CustomerDAO();
	List<Employee> listShipper= new ArrayList<>();
	DecimalFormat formatter = new DecimalFormat("###,###.00");
	
		
		
	
      out.write("\n");
      out.write("	<h2 style= \"margin-right: 500px;\" class=\"Title-view\">Đơn Hàng</h2>\n");
      out.write("	<div class=\"search-ifo\">\n");
      out.write("		<input id=\"text-Search\" placeholder=\"Search...\">\n");
      out.write("		<button id=\"btn-Search\">\n");
      out.write("			<i class=\"fas fa-search\"></i>\n");
      out.write("		</button>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"clear-float\"></div>\n");
      out.write("	<hr style=\"margin-top: 0px;\">\n");
      out.write("	\n");
      out.write("\n");
      out.write("  <ul class=\"nav nav-tabs\">\n");
      out.write("    <li><a id=\"trigger1Click\" data-toggle=\"tab\" href=\"#home\">ĐƠN ĐANG CHỜ DUYỆT</a></li>\n");
      out.write("    <li><a id=\"trigger2Click\" data-toggle=\"tab\" href=\"#menu1\">ĐƠN ĐANG SHIP</a></li>\n");
      out.write("    <li><a id=\"trigger3Click\" data-toggle=\"tab\" href=\"#menu2\">ĐƠN HOÀN THÀNH</a></li>\n");
      out.write("  </ul>\n");
      out.write("\n");
      out.write("  <div class=\"tab-content\">\n");
      out.write("    <div id=\"home\" class=\"tab-pane fade in active\">\n");
      out.write("     \n");
      out.write("     <div class=\"content-page\">\n");
      out.write("\n");
      out.write("		<p class=\"head-table\">Danh sách Đơn Đang Chờ Duyệt</p>\n");
      out.write("\n");
      out.write("		<div style=\"height: 480px\" class=\"content-table table-responsive\">\n");
      out.write("				<table class=\"table table-striped edit-table-view\" >\n");
      out.write("			\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"width: 10%\">Mã Đơn</th>\n");
      out.write("						<th  style=\"width: 15%\">Tên Khách Hàng</th>\n");
      out.write("						<th style=\"width: 15%\">Ngày đặt</th>\n");
      out.write("						<th style=\"width: 10%\">Tổng tiền ($)</th>\n");
      out.write("						<th style=\"width: 35%\">Thông tin</th>\n");
      out.write("						<th style=\"width: 10%\"></th>\n");
      out.write("						<th style=\"width: 5%\"></th>\n");
      out.write("						\n");
      out.write("						</tr>\n");
      out.write("				 	");

				 	listOrders= orderDAO.listOrderBystatus(0);
					  for (int i = 0; i < listOrders.size(); i++) {  
						  int idOrder=listOrders.get(i).getId();
						  int customerID=listOrders.get(i).getCustomerID();
						  String Date=listOrders.get(i).getCreate_date();
						  int total=listOrders.get(i).getTotal();
						  String name=listOrders.get(i).getName();
						  String phone=listOrders.get(i).getPhone();
						  String address=listOrders.get(i).getAddress();
						  String time=listOrders.get(i).getTime();
						  customer= customerDAO.customerByID(customerID);
						  String customerName= customer.getName();
						  String customerEmail= customer.getEmail();
							
					
					
      out.write(" \n");
      out.write("					<tr class=\" tableViewContent\" >\n");
      out.write("					\n");
      out.write("						<td >");
      out.print(idOrder);
      out.write("</td>\n");
      out.write("						<td class=\"colName\" >");
      out.print(customerName );
      out.write("</td>\n");
      out.write("						<td class=\"colNgayDat\">");
      out.print(Date);
      out.write("</td>\n");
      out.write("						<td class=\"colTotal\">$");
      out.print(formatter.format(total));
      out.write("</td>\n");
      out.write("						<td class=\"colInfo\"><ul>\n");
      out.write("						<li>Tên: ");
      out.print(name );
      out.write("</li>\n");
      out.write("						<li>SDT: ");
      out.print(phone );
      out.write("</li>\n");
      out.write("						<li>Địa Chỉ: ");
      out.print(address );
      out.write("</li>\n");
      out.write("						<li>Ngày giao: ");
      out.print(time );
      out.write("</li>\n");
      out.write("						</ul>\n");
      out.write("						</td>\n");
      out.write("						<td><a href=\"#\" data-id=\"");
      out.print(idOrder);
      out.write("\" class=\"viewOrderDetail\">Xem chi tiết</a></td>\n");
      out.write("						<td>\n");
      out.write("						<button id=\"btnShipper");
      out.print(idOrder );
      out.write("\" class=\"btn btn-primary btnShipper\"\n");
      out.write("								data-id=\"");
      out.print(idOrder);
      out.write("\" data-email=");
      out.print(customerEmail );
      out.write("\n");
      out.write("								>Duyệt</button>\n");
      out.write("							\n");
      out.write("						</td>\n");
      out.write("						\n");
      out.write("\n");
      out.write("					</tr>\n");
      out.write("				\n");
      out.write("				");

					}
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("	  	\n");
      out.write("		<div class=\"modal fade\" id=\"shipperModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" style=\"display: none\">\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Duyệt Đơn Hàng</h5>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("					<p>Chọn nhân viên giao hàng</p>\n");
      out.write("					<p style=\"color:red\">Vui lòng chọn nhân viên giao hàng có ít đơn hàng nhất</p>\n");
      out.write("						<select id=\"cmbShipper\"> \n");
      out.write("						");
 
							listShipper= employeeDAO.listShipper();
							for(int i=0;i<listShipper.size();i++){
								int count= orderDAO.countOrderByShipper(listShipper.get(i).getId());
								
							
      out.write("\n");
      out.write(" 							 <option value=\"");
      out.print(listShipper.get(i).getId() );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(listShipper.get(i).getName());
      out.write("  -  Đang giao ( ");
      out.print(count );
      out.write(" đơn hàng )</option>\n");
      out.write("  							");

							}
  							
      out.write("\n");
      out.write("						</select>\n");
      out.write("	\n");
      out.write("				</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"\n");
      out.write("							data-button=\"shipper\" id=\"shipper\">Có</button>\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Không</button>\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div> \n");
      out.write("     \n");
      out.write("     </div>\n");
      out.write("    <div id=\"menu1\" class=\"tab-pane fade\">\n");
      out.write("    \n");
      out.write("     <div class=\"content-page\">\n");
      out.write("\n");
      out.write("		<p class=\"head-table\">Danh sách Đơn Đang Ship</p>\n");
      out.write("\n");
      out.write("		<div style=\"height: 480px\" class=\"content-table table-responsive\">\n");
      out.write("				<table class=\"table table-striped edit-table-view\" >\n");
      out.write("			\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"width: 5%\">Mã Đơn</th>\n");
      out.write("						<th style=\"width: 15%\">Tên Khách Hàng</th>\n");
      out.write("						<th style=\"width: 15%\">Tên Shipper</th>\n");
      out.write("						<th style=\"width: 10%\">Ngày đặt</th>\n");
      out.write("						<th style=\"width: 10%\">Tổng tiền</th>\n");
      out.write("						<th style=\"width: 30%\">Thông tin</th>\n");
      out.write("						<th style=\"width: 10%\"></th>\n");
      out.write("						<th style=\"width: 5%\"></th>\n");
      out.write("						</tr>\n");
      out.write("				 	");

				 		listOrders= orderDAO.listOrderBystatus(1);
					  for (int i = 0; i < listOrders.size(); i++) {  
						  int idOrder=listOrders.get(i).getId();
						  int customerID=listOrders.get(i).getCustomerID();
						  int idShipper=listOrders.get(i).getShipperID();
						  String Date=listOrders.get(i).getCreate_date();
						  int total=listOrders.get(i).getTotal();
						  String name=listOrders.get(i).getName();
						  String phone=listOrders.get(i).getPhone();
						  String address=listOrders.get(i).getAddress();
						  String time=listOrders.get(i).getTime(); 
						  customer= customerDAO.customerByID(customerID);
						  String customerName= customer.getName();
						  employee= employeeDAO.employeeByID(idShipper);
						  String shipperName= employee.getName();
					
					
      out.write(" \n");
      out.write("					<tr class=\" tableViewContent\" >\n");
      out.write("					\n");
      out.write("						<td >");
      out.print(idOrder );
      out.write("</td>\n");
      out.write("						<td class=\"colName\">");
      out.print(customerName );
      out.write("</td>\n");
      out.write("						<td >");
      out.print(shipperName);
      out.write("</td>\n");
      out.write("						<td class=\"colNgayDat\">");
      out.print(Date);
      out.write("</td>\n");
      out.write("						<td class=\"colTotal\">$");
      out.print(formatter.format(total));
      out.write("</td>\n");
      out.write("						<td class=\"colInfo\"><ul>\n");
      out.write("						<li>Tên: ");
      out.print(name );
      out.write("</li>\n");
      out.write("						<li>SDT: ");
      out.print(phone);
      out.write("</li>\n");
      out.write("						<li>Địa Chỉ: ");
      out.print(address );
      out.write("</li>\n");
      out.write("						<li>Ngày giao: ");
      out.print(time);
      out.write("</li>\n");
      out.write("						</ul>\n");
      out.write("						</td>\n");
      out.write("								<td><a href=\"#\" data-id=\"");
      out.print(idOrder);
      out.write("\" class=\"viewOrderDetail\">Xem chi tiết</a></td>\n");
      out.write("						<td>\n");
      out.write("						<button id=\"btnComplete");
      out.print( i);
      out.write("\" class=\"btn btn-primary btnComplete\"\n");
      out.write("								data-id=\"");
      out.print(idOrder);
      out.write("\"\n");
      out.write("								data-button=\"complete\" onclick =\"complete('");
      out.print( i  );
      out.write("')\"\n");
      out.write("								>Duyệt</button>\n");
      out.write("							\n");
      out.write("						</td>\n");
      out.write("\n");
      out.write("					</tr>\n");
      out.write("				\n");
      out.write("				");

					  }
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	</div> \n");
      out.write("    \n");
      out.write("      </div>\n");
      out.write("      	<div class=\"modal fade\" id=\"duyetModal\" role=\"dialog\">\n");
      out.write("		<div class=\"modal-dialog modal-center\" role=\"document\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\" >\n");
      out.write("					<h5 class=\"modal-title\">XÁC NHẬN</h5>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("					<p>Bạn có chắc chắn muốn xác nhận đơn hoàn thành không ? </p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" id=\"btnduyetComplete\" class=\"btn btn-primary\">Đồng Ý</button>\n");
      out.write("						<button type=\"button\" class=\"btn\"\n");
      out.write("						data-dismiss=\"modal\">Hủy</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("    <div id=\"menu2\" class=\"tab-pane fade\">\n");
      out.write("    \n");
      out.write("     <div class=\"content-page\">\n");
      out.write("\n");
      out.write("		<p class=\"head-table\">Danh sách Đơn Đã Hoàn Thành</p>\n");
      out.write("\n");
      out.write("		<div style=\"height: 480px\" class=\"content-table table-responsive\">\n");
      out.write("				<table class=\"table table-striped edit-table-view\" >\n");
      out.write("			\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"width: 5%\">Mã Đơn</th>\n");
      out.write("						<th style=\"width: 13%\">Khách Hàng</th>\n");
      out.write("						<th style=\"width: 13%\">Nhân Viên Duyệt</th>\n");
      out.write("						<th style=\"width: 13%\">Shipper</th>\n");
      out.write("						<th style=\"width: 10%\">Ngày đặt</th>\n");
      out.write("						<th style=\"width: 7%\">Tổng tiền</th>\n");
      out.write("						<th style=\"width: 24%\">Thông tin</th>\n");
      out.write("						<th style=\"width: 10%\"></th>\n");
      out.write("						</tr>\n");
      out.write("				 	");

				 		listOrders= orderDAO.listOrderBystatus(2);
					  for (int i = 0; i < listOrders.size(); i++) {  
						  int idOrder=listOrders.get(i).getId();
						  int customerID=listOrders.get(i).getCustomerID();
						  int idShipper=listOrders.get(i).getShipperID();
						  int idEmployee=listOrders.get(i).getEmployeeID();
						  String Date=listOrders.get(i).getCreate_date();
						  int total=listOrders.get(i).getTotal();
						  String name=listOrders.get(i).getName();
						  String phone=listOrders.get(i).getPhone();
						  String address=listOrders.get(i).getAddress();
						  String time=listOrders.get(i).getTime(); 
						  customer= customerDAO.customerByID(customerID);
						  String customerName= customer.getName();
						  employee= employeeDAO.employeeByID(idShipper);
						  String shipperName= employee.getName();
						  employee= employeeDAO.employeeByID(idEmployee);
						  String employeeName= employee.getName();
					
					
      out.write(" \n");
      out.write("					<tr class=\" tableViewContent\" >\n");
      out.write("					\n");
      out.write("						<td >");
      out.print(idOrder);
      out.write("</td>\n");
      out.write("						<td class=\"colName\">");
      out.print(customerName );
      out.write("</td>\n");
      out.write("						<td>");
      out.print(employeeName );
      out.write("</td>\n");
      out.write("						<td >");
      out.print(shipperName );
      out.write("</td>\n");
      out.write("						<td class=\"colNgayDat\">");
      out.print(Date);
      out.write("</td>\n");
      out.write("						<td class=\"colTotal\">$");
      out.print(formatter.format(total));
      out.write("</td>\n");
      out.write("						<td class=\"colInfo\"><ul>\n");
      out.write("						<li>Tên: ");
      out.print(name );
      out.write("</li>\n");
      out.write("						<li>SDT: ");
      out.print(phone );
      out.write("</li>\n");
      out.write("						<li>Địa Chỉ: ");
      out.print(address );
      out.write("</li>\n");
      out.write("						<li>Ngày giao: ");
      out.print(time );
      out.write("</li>\n");
      out.write("						</ul>\n");
      out.write("						</td>\n");
      out.write("						<td><a href=\"#\" data-id=\"");
      out.print(idOrder);
      out.write("\" class=\"viewOrderDetail\">Xem chi tiết</a></td>\n");
      out.write("					</tr>\n");
      out.write("				\n");
      out.write("				");

					  }
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</div> \n");
      out.write("    \n");
      out.write("       </div>\n");
      out.write("   \n");
      out.write("  </div>\n");
      out.write(" <script>\n");
      out.write(" $(document).ready(function(){\n");
      out.write("\n");
      out.write("		$(\".viewOrderDetail\").click(function(){\n");
      out.write("			var id=$(this).attr(\"data-id\")\n");
      out.write("			console.log(1)\n");
      out.write("			$(\"#content\").load(\"../Admin/OrderDetail.jsp?id=\"+id)\n");
      out.write("		})\n");
      out.write(" })\n");
      out.write("	\n");
      out.write("</script> \n");
      out.write("	<script src=\"../JsAdmin/OrderAdmin.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
