/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-27 14:11:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.project.ecommerce.dao.ProductDAO;
import com.project.ecommerce.model.Product;
import com.project.ecommerce.dao.Promotion_detailDAO;
import com.project.ecommerce.model.Promotion_detail;
import com.project.ecommerce.dao.PromotionDAO;
import com.project.ecommerce.model.Promotion;
import java.text.DecimalFormat;
import com.project.ecommerce.dao.CustomerDAO;
import com.project.ecommerce.model.Customer;
import com.project.ecommerce.dao.EmployeeDAO;
import com.project.ecommerce.model.Employee;
import com.project.ecommerce.dao.OrderDAO;
import com.project.ecommerce.model.Order;
import com.project.ecommerce.dao.BrandDAO;
import com.project.ecommerce.model.Brand;
import com.project.ecommerce.dao.CategoryDAO;
import com.project.ecommerce.model.Category;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class PromotionDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Admin/../CssAdmin/fstyle.css", Long.valueOf(1699944475685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.ecommerce.dao.BrandDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Category");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.project.ecommerce.dao.ProductDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Customer");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.project.ecommerce.model.Promotion_detail");
    _jspx_imports_classes.add("com.project.ecommerce.model.Brand");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CategoryDAO");
    _jspx_imports_classes.add("com.project.ecommerce.dao.EmployeeDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.project.ecommerce.model.Product");
    _jspx_imports_classes.add("com.project.ecommerce.dao.CustomerDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Employee");
    _jspx_imports_classes.add("com.project.ecommerce.dao.PromotionDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Order");
    _jspx_imports_classes.add("com.project.ecommerce.dao.OrderDAO");
    _jspx_imports_classes.add("com.project.ecommerce.dao.Promotion_detailDAO");
    _jspx_imports_classes.add("com.project.ecommerce.model.Promotion");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"../Js/jquery.twbsPagination.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>");
      out.write("@charset \"UTF-8\";\n");
      out.write("\n");
      out.write("header {\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content h3 {\n");
      out.write("	float: left;\n");
      out.write("	margin: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 {\n");
      out.write("	float: right;\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li {\n");
      out.write("	list-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li a {\n");
      out.write("	color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-content .dropdown1 ul li a:hover {\n");
      out.write("	cursor: pointer;\n");
      out.write("	background-color: #EEEEEE;\n");
      out.write("	color: blue;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown:hover .dropdown-content {\n");
      out.write("	display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content {\n");
      out.write("	position: absolute;\n");
      out.write("	background-color: white;\n");
      out.write("	z-index: 1;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul {\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li {\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background-color: white;\n");
      out.write("	width: 140%;\n");
      out.write("	float: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li a {\n");
      out.write("	font-size: 14px;\n");
      out.write("	padding: 14px;\n");
      out.write("	display: block;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-content ul li a i {\n");
      out.write("	margin-right: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sub-dropdown {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".clear-float {\n");
      out.write("	clear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section {\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu {\n");
      out.write("	padding: 0px;\n");
      out.write("	border-right: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content {\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .layout {\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul {\n");
      out.write("	padding: 0;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li {\n");
      out.write("	list-style: none;\n");
      out.write("	padding: 10px;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li:hover {\n");
      out.write("	background-color: #EEEEEE;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li a {\n");
      out.write("	padding-left: 10px;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .menu ul li a i {\n");
      out.write("	margin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content {\n");
      out.write("	background-color: white;\n");
      out.write("	padding: 30px 30px 20px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .Title-view {\n");
      out.write("	float: left;\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Title-add {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".Title-edit {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-bottom: 1px solid lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo {\n");
      out.write("	float: right;\n");
      out.write("	padding: 5px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo input {\n");
      out.write("	float: left;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-bottom-left-radius: 5px;\n");
      out.write("	padding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-ifo button {\n");
      out.write("	padding: 5px 10px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("	border-bottom-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .content-page {\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#section-content .content .content-page .head-table {\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("	text-align: left;\n");
      out.write("	padding: 10px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background-color: #F8F8F8;\n");
      out.write("	border-bottom: 0;\n");
      out.write("	margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content-table {\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	padding: 10px;\n");
      out.write("	width: 100%;\n");
      out.write("	padding-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view th {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	border-top: 0;\n");
      out.write("	border-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-view td {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	border-top: 0;\n");
      out.write("	border-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content .table-head {\n");
      out.write("	margin-top: 20px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	background: #F8F8F8;\n");
      out.write("	border-top-left-radius: 5px;\n");
      out.write("	border-top-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-head p {\n");
      out.write("	margin-bottom: 0;\n");
      out.write("	padding: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".table-content {\n");
      out.write("	padding-top: 10px;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("	border-left: 1px lightgray solid;\n");
      out.write("	border-bottom: 1px lightgray solid;\n");
      out.write("	border-right: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content input, select{\n");
      out.write("	padding: 0 5px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write(".table-content textarea {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	border: 1px solid lightgray;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content h6 {\n");
      out.write("	margin-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add td {\n");
      out.write("	padding: 10px 10px 0 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add input {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	width: 70%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add textarea {\n");
      out.write("	padding: 0 5px;\n");
      out.write("	border: 1px lightgray solid;\n");
      out.write("	width: 70%;\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add .button-control {\n");
      out.write("	padding: 10px 10px 20px 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add .button-control button {\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 0px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	color: white;\n");
      out.write("	background-color: #00CC33;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".alert {\n");
      out.write("	color: red;\n");
      out.write("	font-size: 12px;\n");
      out.write("	font-weight: 400;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".edit-table-add p {\n");
      out.write("	margin: 0;\n");
      out.write("	border: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table-content p {\n");
      out.write("	margin: 0;\n");
      out.write("	border: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background-color: #F5F5F5;\n");
      out.write("	/* width: 100%; */\n");
      out.write("	height: 100%;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	width: 100%;\n");
      out.write("	margin: auto;\n");
      out.write("	padding-bottom: 30px;\n");
      out.write("	padding-top: 5%;\n");
      out.write("	background: #F8F8F8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".label {\n");
      out.write("	height: 10%;\n");
      out.write("	width: 36%;\n");
      out.write("	margin: auto;\n");
      out.write("	background: #F5F5F5;\n");
      out.write("	border-radius: 5px 5px 0 0;\n");
      out.write("	border: 2px solid #DDDDDD;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".label p {\n");
      out.write("	margin-left: 5%;\n");
      out.write("	font-size: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".remember {\n");
      out.write("	margin-left: 6%;\n");
      out.write("	margin-bottom: 5%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal .modal-dialog{\n");
      out.write("	width: 100%;\n");
      out.write("    margin: auto;\n");
      out.write("    top: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* .content-table .td-update button{\n");
      out.write("	padding: 5px;\n");
      out.write("    border: 0px;\n");
      out.write("    width:60px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    color: white;\n");
      out.write("    background-color: #007bff;\n");
      out.write("} */\n");
      out.write(".modal-header{\n");
      out.write("	background-color:cadetblue; \n");
      out.write("	color:white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#pagination {\n");
      out.write("		display: flex;\n");
      out.write("		display: -webkit-flex; /* Safari 8 */\n");
      out.write("		flex-wrap: wrap;\n");
      out.write("		-webkit-flex-wrap: wrap; /* Safari 8 */\n");
      out.write("		justify-content: center;\n");
      out.write("		-webkit-justify-content: center;\n");
      out.write("	}\n");
      out.write("/* ---------abc-------- */\n");
      out.write(".modal-title{\n");
      out.write("	font-size:20px;\n");
      out.write("}\n");
      out.write(".modal-body, .modal-body h6 {\n");
      out.write("	font-size:16px;\n");
      out.write("}\n");
      out.write(".modal-body input{\n");
      out.write("	width: 100%;\n");
      out.write("    height: 30px;\n");
      out.write("    border: 1px solid lightgray;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("}\n");
      out.write(".modal-body select{\n");
      out.write("	width:100%;\n");
      out.write("	height:30px;\n");
      out.write("	margin:0;\n");
      out.write("	 border: 1px solid lightgray;\n");
      out.write("    border-radius: 5px;\n");
      out.write("}\n");
      out.write(".btn-addcontent{\n");
      out.write("	position: absolute;\n");
      out.write("	    top: 37px;\n");
      out.write("    right: 400px;\n");
      out.write("}\n");
      out.write(" .table-content h6,\n");
      out.write(".table-content h5{\n");
      out.write("	font-size:16px;\n");
      out.write("	margin-left:15px;\n");
      out.write("}\n");
      out.write(".table-content input{\n");
      out.write("	height:30px;\n");
      out.write("}");
      out.write("</style> \n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Promotion</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	 ");

		Employee user = (Employee) session.getAttribute("employeeSession");
		 if(user == null){			
			response.sendRedirect("LoginAdmin.jsp");
			return;
		} 
	Employee employee= new Employee();
	EmployeeDAO employeeDAO= new EmployeeDAO();
	Promotion promotion= new Promotion();
	PromotionDAO promotionDAO= new PromotionDAO();
	List<Promotion> listPromotions = new ArrayList<>();
	Promotion_detail promotion_detail= new Promotion_detail();
	Promotion_detailDAO promotion_detailDAO= new Promotion_detailDAO();
	List<Promotion_detail> listPromotion_detail = new ArrayList<>();
	int a= (int) session.getAttribute("cmbPromotion"); 
	promotion= promotionDAO.PromotionByID(a);
	SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
	Date dateEndPromotion = formatter.parse(promotion.getDateEnd());
	Date dateStartPromotion = formatter.parse(promotion.getDateStart());
	ProductDAO productDAO= new ProductDAO();
	Category category= new Category();
	CategoryDAO categoryDAO= new CategoryDAO();
	List<Category> lisCategories = new ArrayList<>();
	
	Date dateCurrent = new Date();
	
	
      out.write("\n");
      out.write("	<span id=\"backtoPromotion\" style=\"float:left; cursor:pointer\"><i class=\"fas fa-backward\"></i> Quay về Đợt Giảm Giá</span><br>\n");
      out.write("	<h2 style= \"margin-right: 100px;\" class=\"Title-view\">Chi Tiết Đợt Giảm Giá (");
      out.print(promotion.getDateStart() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(promotion.getDateEnd() );
      out.write(")</h2>\n");
      out.write("		<button data-id=");
      out.print(a );
      out.write(" \n");
      out.write("		");
if(dateCurrent.compareTo(dateEndPromotion)>0){ 
      out.write("\n");
      out.write("		id=\"noAdd\" ");
 }else { 
      out.write(" id=\"btn-addcontent\"");
} 
      out.write("\n");
      out.write("		class=\" btn btn-primary\" >Thêm Sản Phẩm</button>\n");
      out.write("	\n");
      out.write("	<div class=\"search-ifo\">\n");
      out.write("		<input id=\"text-Search\" placeholder=\"Search...\">\n");
      out.write("		<button id=\"btn-Search\">\n");
      out.write("			<i class=\"fas fa-search\"></i>\n");
      out.write("		</button>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"clear-float\"></div>\n");
      out.write("	<hr style=\"margin-top: 0px;\">\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write("    <div class=\"content-page\">\n");
      out.write("\n");
      out.write("		<p class=\"head-table\">Danh sách Chi Tiết Sản Phẩm Giảm Giá</p>\n");
      out.write("		\n");
      out.write("		<div style=\"height: 480px\" class=\"content-table table-responsive\">\n");
      out.write("				<table class=\"table table-striped edit-table-view\" >\n");
      out.write("			\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"width: 20%\">Mã Sản Phẩm</th>\n");
      out.write("						<th style=\"width: 40%\">Tên Sản Phẩm</th>\n");
      out.write("						<th style=\"width: 20%\">Thể Loại</th>\n");
      out.write("						<th style=\"width: 10%\">Giảm (%)</th>\n");
      out.write("						<th style=\"width: 5%\"></th>\n");
      out.write("						<th style=\"width: 5%\"></th>\n");
      out.write("						</tr>\n");
      out.write("				 	");
	  
				 
				 		
				 		listPromotion_detail= promotion_detailDAO.listPromotion_detailbyID(a);
				 			      
				 	      for (int i = 0; i < listPromotion_detail.size(); i++) {  
						  String productID= listPromotion_detail.get(i).getProductID();
						  int idPromotion= listPromotion_detail.get(i).getPromotionID();
						  int percent_promotion= listPromotion_detail.get(i).getPercent_promotion();
						  String productName= listPromotion_detail.get(i).getProcductName();
						  category = categoryDAO.categoryByidProduct(productID);
						  
						
					
      out.write(" \n");
      out.write("					<tr class=\"contentPage2 tableViewContent\" >\n");
      out.write("					\n");
      out.write("						<td >");
      out.print(productID );
      out.write("</td>\n");
      out.write("						<td class=\"colName\">");
      out.print(productName );
      out.write("</td>\n");
      out.write("						<td >");
      out.print(category.getName() );
      out.write("</td>	\n");
      out.write("						<td class=\"colPercent\" >");
      out.print(percent_promotion);
      out.write("</td>\n");
      out.write("						<td >\n");
      out.write("						<button  id=\"btn-edit");
      out.print(i);
      out.write("\" class=\"btn btn-primary btn-edit\"\n");
      out.write("						");
if(dateCurrent.compareTo(dateStartPromotion)>0){ 
      out.write("\n");
      out.write("							style=\"display:none\"\n");
      out.write("							");
} 
      out.write("\n");
      out.write("								data-i=\"");
      out.print(i );
      out.write("\"\n");
      out.write("								data-productId=\"");
      out.print(productID);
      out.write("\" \n");
      out.write("								data-promotionId=\"");
      out.print(idPromotion );
      out.write("\"\n");
      out.write("								data-name=\"");
      out.print(percent_promotion);
      out.write("\"\n");
      out.write("								data-ten=\"");
      out.print(productName );
      out.write("\"\n");
      out.write("						>Sửa</button>\n");
      out.write("						</td>\n");
      out.write("						<td>\n");
      out.write("						<button id=\"btn-delete");
      out.print(i);
      out.write("\" class=\"btn btn-delete\"\n");
      out.write("						");
if(dateCurrent.compareTo(dateStartPromotion)>0){ 
      out.write("\n");
      out.write("							style=\"display:none\"\n");
      out.write("							");
} 
      out.write("\n");
      out.write("								data-i=\"");
      out.print(i );
      out.write("\"\n");
      out.write("								data-name=\"");
      out.print(productName);
      out.write("\"\n");
      out.write("								data-productId=\"");
      out.print(productID);
      out.write("\" \n");
      out.write("								data-promotionId=\"");
      out.print(idPromotion );
      out.write("\"\n");
      out.write("							>Xóa</button>\n");
      out.write("							\n");
      out.write("						</td>\n");
      out.write("\n");
      out.write("					</tr>\n");
      out.write("				\n");
      out.write("				");

					  }
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<ul style=\"margin-top: 20px;display: flex;\" id=\"pagination2\"  class=\"justify-content-center\">\n");
      out.write("	  	</ul>\n");
      out.write("	</div> \n");
      out.write("	<div class=\"modal fade\" id=\"deleteModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" style=\"display: none\">\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Xóa Sản Phẩm Trong Đợt Giảm Giá</h5>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("					<span>Bạn có muốn xóa </span><span id=\"alertDelete\"> </span> <span>ra khỏi đợt giảm giá</span>\n");
      out.write("				</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"\n");
      out.write("							data-button=\"delete\" id=\"delete\">Có</button>\n");
      out.write("						<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Không</button>\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"modal fade\" id=\"editPostModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" >\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<form class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Sửa Sản Phẩm Trong Đợt Giảm Giá</h5>\n");
      out.write("						 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("					<h6 >\n");
      out.write("							Tên Sản Phẩm\n");
      out.write("							\n");
      out.write("						</h6>\n");
      out.write("					\n");
      out.write("						\n");
      out.write("						<input type=\"text\" readonly id=\"edit-ten\" style=\"width: 100%\" />\n");
      out.write("						<h6 >\n");
      out.write("							Giảm (%)\n");
      out.write("							\n");
      out.write("						</h6>\n");
      out.write("					\n");
      out.write("						\n");
      out.write("						<input type=\"number\"  id=\"edit-name\" style=\"width: 100%\" />\n");
      out.write("						<p class=\"alert\" id = \"alert_name\" style=\"margin: 0; padding: 0;\"> </p>	\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-footer\">					\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" id=\"edit\"\n");
      out.write("								 data-button=\"edit\">Đồng Ý</button>\n");
      out.write("						<button type=\"button\" id=\"reset-edit\" class=\"btn btn-default\">Phục Hồi</button>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("     	<div class=\"modal fade\" id=\"addViewContentModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("			aria-hidden=\"true\" >\n");
      out.write("			<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("				<form class=\"modal-content\">\n");
      out.write("					<div class=\"modal-header\">\n");
      out.write("						<h5 class=\"modal-title\">Thêm Sản Phẩm Giảm Giá</h5>\n");
      out.write("						 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("					\n");
      out.write("					<!-- --------- -->\n");
      out.write("						<p>Chọn Thể Loại</p>\n");
      out.write("						\n");
      out.write("							<select id=\"cmbCategory\" onchange=\"cmbChanged()\" style=\"margin-bottom:10px\"> \n");
      out.write("						");
  	lisCategories= categoryDAO.listCategory();
								for(int i=0;i<lisCategories.size();i++){
								int idCate= lisCategories.get(i).getId();
								String nameCate= lisCategories.get(i).getName();
								
							
      out.write("\n");
      out.write(" 							 <option value=\"");
      out.print(idCate);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(nameCate);
      out.write("</option>\n");
      out.write("  							");

							}
  							
      out.write("\n");
      out.write("						</select>\n");
      out.write("						<div id=\"cmbShowProduct\">\n");
      out.write("						\n");
      out.write("						</div>\n");
      out.write("						<h6 >\n");
      out.write("							Giảm (%)\n");
      out.write("						</h6>\n");
      out.write("						<input type=\"number\"  id=\"text-percent\" style=\"width: 100%\" />\n");
      out.write("						<p class=\"alert\" id =\"alertadd_percent\" style=\"margin: 0; padding: 0;\"> </p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" id=\"add\"\n");
      out.write("								 data-button=\"add\">Đồng Ý</button>\n");
      out.write("							<button type=\"reset\" id=\"reset-add\" class=\"btn btn-default\">Phục Hồi </button>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("<div class=\"modal fade\" id=\"noAddModal\" role=\"dialog\">\n");
      out.write("		<div class=\"modal-dialog modal-center\" role=\"document\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\" style=\"background-color:brown\">\n");
      out.write("					<h5 class=\"modal-title\">LỖI</h5>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("					<p>Không thể thêm sản phẩm vì đợt giảm đã hết</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("						data-dismiss=\"modal\">OK</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("		\n");
      out.write(" <script>\n");
      out.write("  $(function () {	\n");
      out.write("	var pageSize = 6; // Hiển thị 6 sản phẩm trên 1 trang\n");
      out.write("	showPage = function(page) {\n");
      out.write("			$(\".contentPage2\").hide();\n");
      out.write("			$(\".contentPage2\").each(function(n) {\n");
      out.write("				if (n >= pageSize * (page - 1) && n < pageSize * page)\n");
      out.write("					$(this).show();\n");
      out.write("			});        \n");
      out.write("		}\n");
      out.write("		showPage(1);\n");
      out.write("		///** Cần truyền giá trị vào đây **///\n");
      out.write("		var totalRows = ");
      out.print(listPromotion_detail.size());
      out.write("; // Tổng số sản phẩm hiển thị\n");
      out.write("		var btnPage = Math.ceil(");
      out.print(listPromotion_detail.size());
      out.write("/pageSize) // Số nút bấm hiển thị di chuyển trang\n");
      out.write("		var iTotalPages = Math.ceil(totalRows / pageSize)\n");
      out.write("\n");
      out.write("		var obj = $('#pagination2').twbsPagination({\n");
      out.write("			totalPages: iTotalPages,\n");
      out.write("			visiblePages: btnPage,\n");
      out.write("			onPageClick: function (event, page) {\n");
      out.write("				/* console.info(page); */\n");
      out.write("				showPage(page);\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	}); \n");
      out.write("\n");
      out.write("	$(document).ready(function(){\n");
      out.write("		$(\"#backtoPromotion\").click(function(){\n");
      out.write("			$(\"#content\").load(\"../Admin/PromotionAdmin.jsp\")\n");
      out.write("		})\n");
      out.write("		//bắt sự kiện click nút delete trong table \n");
      out.write("		$(\".btn-delete\").click(function() {\n");
      out.write("			\n");
      out.write("			var i = $(this).attr(\"data-i\")\n");
      out.write("			var name = $(this).attr(\"data-name\")\n");
      out.write("			var str=\"#btn-delete\"+i\n");
      out.write("			$('#delete').val(str);\n");
      out.write("			$('#alertDelete').html(name)\n");
      out.write("			$(\"#deleteModal\").modal('show')\n");
      out.write("		})\n");
      out.write("		$(\"#delete\").click(function() {\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			var str = $('#delete').val();\n");
      out.write("			var idProduct = $(str).attr(\"data-productId\")\n");
      out.write("			var idPromotion = $(str).attr(\"data-promotionId\")\n");
      out.write("			var dataButton = $(this).attr('data-button');\n");
      out.write("\n");
      out.write("			console.log(idProduct)\n");
      out.write("			console.log(idPromotion)\n");
      out.write("			console.log(dataButton)\n");
      out.write("			$.ajax({\n");
      out.write("				type : \"post\",\n");
      out.write("				url : \"/ShopSmartPhone/promotionDetailServlet\",\n");
      out.write("				data : {\n");
      out.write("					idProduct : idProduct,\n");
      out.write("					idPromotion : idPromotion,\n");
      out.write("					dataButton : dataButton\n");
      out.write("				},\n");
      out.write("				success : function(response) {\n");
      out.write("					if (response == \"success\") {\n");
      out.write("					 	\n");
      out.write("						$('.modal-backdrop').remove()\n");
      out.write("						$(\"#content\").load(\"../Admin/PromotionDetail.jsp\")\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		})\n");
      out.write("		$(\"#noAdd\").click(function(){\n");
      out.write("			$(\"#noAddModal\").modal('show')\n");
      out.write("			\n");
      out.write("		})\n");
      out.write("		//bắt sự kiện click nút Add trong table \n");
      out.write("		$(\"#btn-addcontent\").click(function() {\n");
      out.write("			var idPromotion= $(this).attr(\"data-id\")\n");
      out.write("			$(\"#add\").val(idPromotion)\n");
      out.write("			$(\"#addViewContentModal\").modal('show')\n");
      out.write("			\n");
      out.write("			$(\"#text-percent\").keypress(function() {\n");
      out.write("				$(\"#alertadd_percent\").html('')\n");
      out.write("			})\n");
      out.write("		})\n");
      out.write("		$(\"#add\").click(function() {\n");
      out.write("			var idPromotion= $('#add').val()\n");
      out.write("			var percent_promotion = $('#text-percent').val()\n");
      out.write("			var idProduct=$('#cmbProduct').val()\n");
      out.write("			var dataButton = $(this).attr('data-button')\n");
      out.write("			var flag = 0;\n");
      out.write("			if(percent_promotion.trim()==\"\"){\n");
      out.write("            	$(\"#alertadd_percent\").html('(* Bạn cần điền % giảm giá *)')\n");
      out.write("            	flag=1;\n");
      out.write("            }\n");
      out.write("			if(percent_promotion>100 || percent_promotion <=0){\n");
      out.write("            	$(\"#alertadd_percent\").html('(* Giảm giá phải nằm trong khoảng 1 đến 100 *)')\n");
      out.write("            	flag=1;\n");
      out.write("            }\n");
      out.write("			if(idProduct==''){\n");
      out.write("				$(\"#alertadd_percent\").html('(* Bạn cần chọn sản phẩm cần giảm giá *)')\n");
      out.write("            	flag=1;\n");
      out.write("			}\n");
      out.write("	        if(flag == 0){\n");
      out.write("			$.ajax({\n");
      out.write("				type : \"post\",\n");
      out.write("				url : \"/ShopSmartPhone/promotionDetailServlet\",\n");
      out.write("				data:{\n");
      out.write("					idPromotion : idPromotion,\n");
      out.write("					idProduct : idProduct,\n");
      out.write("					percent_promotion : percent_promotion,\n");
      out.write("					dataButton: dataButton\n");
      out.write("				},\n");
      out.write("				success : function(response) {\n");
      out.write("					if (response == \"success\") {\n");
      out.write("						$(\"#addViewContentModal\").modal('hide')\n");
      out.write("						$('.modal-backdrop').remove() \n");
      out.write("						$(\"#content\").load(\"../Admin/PromotionDetail.jsp\")\n");
      out.write("					}\n");
      out.write("					else if(response == \"exits\"){\n");
      out.write("						$(\"#alertadd_percent\").html('(* Sản phẩm đã có trong đợt giảm giá này *)')\n");
      out.write("					}\n");
      out.write("					else if(response == \"fail\"){\n");
      out.write("						$(\"#alertadd_percent\").html('(* Đã có lỗi xảy ra *)')\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("	       }\n");
      out.write("	    	\n");
      out.write("		})\n");
      out.write("		//bắt sự kiện click nút Edit trong table \n");
      out.write("		$(\".btn-edit\").click(function() {\n");
      out.write("			$(\"#editPostModal\").modal('show')\n");
      out.write("			t = $(this).parent().parent('tr');\n");
      out.write("			var i = $(this).attr(\"data-i\")\n");
      out.write("			var name = $(this).attr(\"data-name\")\n");
      out.write("			var ten = $(this).attr(\"data-ten\")\n");
      out.write("			$('#edit').val(i)\n");
      out.write("			$('#edit-name').val(name)\n");
      out.write("			$('#edit-ten').val(ten)\n");
      out.write("\n");
      out.write("			$(\"#reset-edit\").click(function(){\n");
      out.write("				$('#edit-name').val(name)\n");
      out.write("			})\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			$(\"#edit-name\").keypress(function() {\n");
      out.write("				$(\"#alert_name\").html('')\n");
      out.write("			})\n");
      out.write("\n");
      out.write("		})\n");
      out.write("		//bắt sự kiện click OK\n");
      out.write("		$(\"#edit\").click(function() {\n");
      out.write("			var i = $('#edit').val()\n");
      out.write("			var name = $('#edit-name').val()\n");
      out.write("			var dataButton = $(this).attr('data-button')\n");
      out.write("			var flag = 0;\n");
      out.write("			var str= \"#btn-edit\"+i\n");
      out.write("			var idProduct =$(str).attr(\"data-productId\")\n");
      out.write("			var idPromotion=$(str).attr(\"data-promotionId\")\n");
      out.write("			 if(name.trim()==\"\"){\n");
      out.write("	            	$(\"#alert_name\").html('(* Bạn cần ghi số % giảm *)')\n");
      out.write("	            	flag = 1;\n");
      out.write("	            }\n");
      out.write("			 if(name>100 || name <=0){\n");
      out.write("	            	$(\"#alert_name\").html('(* % phải nằm trong khoảng từ 1 tới 100 *)')\n");
      out.write("	            	flag = 1;\n");
      out.write("	            }\n");
      out.write("\n");
      out.write("	        if(flag == 0){\n");
      out.write("			$.ajax({\n");
      out.write("				type : \"post\",\n");
      out.write("				url : \"/ShopSmartPhone/promotionDetailServlet\",\n");
      out.write("				data : {\n");
      out.write("					idProduct : idProduct,\n");
      out.write("					idPromotion : idPromotion,\n");
      out.write("					perent_promotion : name,\n");
      out.write("					dataButton : dataButton\n");
      out.write("				},\n");
      out.write("				success : function(response) {\n");
      out.write("					if (response == \"success\") {\n");
      out.write("						$(\"#editPostModal\").modal('hide')\n");
      out.write("						$('.modal-backdrop').remove()  \n");
      out.write("						$(str).attr('data-name',name)\n");
      out.write("						t.find('.colPercent').html(name);\n");
      out.write("					}\n");
      out.write("					else if(response == \"trung\"){\n");
      out.write("						$(\"#alert_name\").html('(* Trùng thể loại *)')\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("	       }\n");
      out.write("	    	\n");
      out.write("		})\n");
      out.write("		//hàm chuyển các giá trị trong col thành chữ thường LowerCase()\n");
      out.write("		$.extend($.expr[\":\"], {\"containsNC\": function(elem, i, match, array) {\n");
      out.write("        return (elem.textContent || elem.innerText || \"\").toLowerCase().indexOf((match[3] || \"\").toLowerCase()) >= 0;\n");
      out.write("			}\n");
      out.write("			});\n");
      out.write("		//bắt sự kiện search, giá trị nhập vào thành chữ thường \n");
      out.write("		$(\"#btn-Search\").click(function() {\n");
      out.write("			var a = $(\"#text-Search\").val().toLowerCase();\n");
      out.write("			    $(\".tableViewContent td.colName:containsNC('\" +a + \"')\").parent().show();\n");
      out.write("		        $(\".tableViewContent td.colName:not(:containsNC('\" +a+ \"'))\").parent().hide();\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("	\n");
      out.write("	$(\"#cmbShowProduct\").load(\"../Admin/cmbCategory.jsp?idCate=1\")\n");
      out.write("\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	function cmbChanged(){\n");
      out.write("	 var x= $(\"#cmbCategory\").val()\n");
      out.write("	 $(\"#cmbShowProduct\").load(\"../Admin/cmbCategory.jsp?idCate=\"+x)\n");
      out.write("}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</script> \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
